### PR TITLE
Remove wix from installer filter

### PR DESCRIPTION
**Pull request by M-Davies**
Signed-off-by: Morgan Davies <morgan.davies@ibm.com>

### CODE REVIEW

**Comment by M-Davies** [comment]
I'm going to try testing this by pushing it through, running some pipelines and reverting if it causes build breaks

**Comment by M-Davies** [comment]
Kicked off some windows pipelines to test
- https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1112/
- https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1001/
- https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk14-pipeline/209/
- https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk15-pipeline/163/

**Comment by M-Davies** [comment]
I've seen two instances where this has failed with the same error as #1834 
- https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-hotspot/635/console
- https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x86-32-hotspot/617/console
Reverting this in https://github.com/AdoptOpenJDK/openjdk-build/pull/1861 and back to the drawing board we go!

**Comment by douph1** [comment]
I'm questioning  myself about / \ ( folder separtor )

**Comment by M-Davies** [comment]
@douph1 You think it could be something to do with windows paths (`\`) vs cygwin/unix paths (`/`)? That doesn't explain why it's intermittent though 🤔

**Pull request merged**
