### PR TITLE
Set GitHub commit status for downstream PR tester jobs

### PR DESCRIPTION
**Pull request by gdams**
Adds status checks for each downstream job to help see the build failures

### CODE REVIEW

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Review by smlambert — APPROVED** [review]

**Review by karianna — APPROVED** [review]
LGTM

**Pull request merged**
