### PR TITLE
Use Groovy's Advanced Sleep

### PR DESCRIPTION
**Pull request by M-Davies**
* Because bash advanced sleep doesn't work here

Follow up to https://github.com/AdoptOpenJDK/openjdk-build/pull/2102
Signed-off-by: Morgan Davies <morgandavies2020@gmail.com>

### CODE REVIEW

**Review by gdams — APPROVED** [review]

**Review by karianna — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
run tests

**Comment by karianna** [comment]
Anyone know why those builds keep aborting?

**Comment by karianna** [comment]
run tests

**Pull request merged**
