### PR TITLE
Add option to generate debug images

### PR DESCRIPTION
**Pull request by milderhc**
Adding `--create-debug-image`  to generate debug symbols archives in the build pipeline.

### CODE REVIEW

**Review by karianna — CHANGES_REQUESTED** [review]
Hi Milder, I think this would _always_ create debug images is that correct?  Does this need to be wrapped in a flag that the user can set/override?

**Comment by andrew-m-leonard** [comment]
> Hi Milder, I think this would _always_ create debug images is that correct? Does this need to be wrapped in a flag that the user can set/override?

@karianna that is the intention yes to always have debug-images, just like we do for openj9.

**Comment by andrew-m-leonard** [comment]
run tests

**Review by karianna — APPROVED** [review]

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
@milderhc the parameterised generators has now been merged, so in order to test this, you will need to re-base your fork on top of the lastest openjdk-build master

**Review by andrew-m-leonard — CHANGES_REQUESTED** [review]
Re-base on openjdk-build master to pickup latest generator changes

**Comment by milderhc** [comment]
run tests

**Comment by M-Davies** [comment]
run tests

**Review by M-Davies — COMMENTED** [review]
https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk8u/job/jdk8u-mac-x64-hotspot/442/console
```
18:25:48  cp: /Users/jenkins/workspace/build-scripts-pr-tester/build-test/jobs/jdk8u/jdk8u-mac-x64-hotspot/workspace/build/src/build/macosx-x86_64-normal-server-release/jdk/objs/java_objs/java.dSYM: No such file or directory
```
Is this related to this change?

**Comment by milderhc** [comment]
This change activates debug symbols creation for all platforms but there is an existent problem with creating them for jdk8u: https://github.com/AdoptOpenJDK/openjdk-build/issues/2331. Should I exclude `--create-debug-image` when building mac jdk8?

**Comment by andrew-m-leonard** [comment]
> This change activates debug symbols creation for all platforms but there is an existing problem with creating them for jdk8u: #2331. Should I exclude `--create-debug-image` when building mac jdk8?

@milderhc this reminded me of something... jdk8 does not support DEBUG_SYMBOLS on MacOS quite the same way, see this openjdk code: https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/83742e9ef3d7274083f8a84c5772b1ea565d06bf/make/common/NativeCompilation.gmk#L443
I think jdk8 macos uses dsymutil rather than objcopy, but I am not entirely sure how it is used, you may need to investigate

**Comment by andrew-m-leonard** [comment]
@milderhc we may also want to check jdk8 AIX is producing debug images, as objcopy is proably not native to AIX either?

**Comment by andrew-m-leonard** [comment]
@milderhc hi Milder, how's it going investigating Mac?

**Comment by milderhc** [comment]
Hi @andrew-m-leonard, I'm looking at it. But I don't understand the fix. We see in the file you mentioned there's no support for mac at all, all the other OS have their if-logic to produce them. The idea would be to add the logic for mac to that file (probably using `dsymutil`)?

**Comment by andrew-m-leonard** [comment]
@milderhc hi Milder, fyi, i've got a jdk8 Mac fix to produce debug symbols now, i'm just testing it...
I'm seeing some other packaging issues, possibly only mac related, but i'm investigating

**Comment by andrew-m-leonard** [comment]
The Mac debug-image archiving is collecting the whole of the jdk, not just the dSYM files. I will compare with openj9

**Comment by andrew-m-leonard** [comment]
AIX has issues as well as the jdk8 configure does not allow "external", i'm correcting that as well.

**Comment by sxa** [comment]
We should also keep an eye on whether the Solaris support works properly on our build machines.

**Comment by andrew-m-leonard** [comment]
> We should also keep an eye on whether the Solaris support works properly on our build machines.

In theory the jdk8u code supports it, but I can't test it until we have a working Solaris build node again: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1865

**Comment by sxa** [comment]
> > We should also keep an eye on whether the Solaris support works properly on our build machines.
> 
> In theory the jdk8u code supports it, but I can't test it until we have a working Solaris build node again: [AdoptOpenJDK/openjdk-infrastructure#1865](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1865)

We still have [Solaris/SPARC](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-sparcv9-hotspot/) - it's unlikely to be different between that an x64

**Comment by andrew-m-leonard** [comment]
> > > We should also keep an eye on whether the Solaris support works properly on our build machines.
> > 
> > 
> > In theory the jdk8u code supports it, but I can't test it until we have a working Solaris build node again: [AdoptOpenJDK/openjdk-infrastructure#1865](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1865)
> 
> We still have [Solaris/SPARC](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-sparcv9-hotspot/) - it's unlikely to be different between that an x64

jdk8 Solaris works: https://ci.adoptopenjdk.net/view/work-in-progress/job/andrew-jdk8u-solaris-sparcv9-hotspot/3/

**Comment by karianna** [comment]
> > > > We should also keep an eye on whether the Solaris support works properly on our build machines.
> > > 
> > > 
> > > In theory the jdk8u code supports it, but I can't test it until we have a working Solaris build node again: [AdoptOpenJDK/openjdk-infrastructure#1865](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1865)
> > 
> > 
> > We still have [Solaris/SPARC](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-sparcv9-hotspot/) - it's unlikely to be different between that an x64
> 
> jdk8 Solaris works: https://ci.adoptopenjdk.net/view/work-in-progress/job/andrew-jdk8u-solaris-sparcv9-hotspot/3/

@andrew-m-leonard Anything left to go on this now?  Milder was tied up for a few days but I can nudge him internally once he frees up.

**Comment by andrew-m-leonard** [comment]
@karianna yes, i've got openjdk patches for jdk/8/11/16/17 to fix the macOS & AIX generation, they are ready for review very shortly

**Comment by andrew-m-leonard** [comment]
openjdk patches to support jdk8 mac and jdk8/11/16/17 AIX debug symbols:
- https://github.com/AdoptOpenJDK/openjdk-jdk8u/pull/16
- https://github.com/AdoptOpenJDK/openjdk-jdk11u/pull/20
- https://github.com/AdoptOpenJDK/openjdk-jdk16/pull/1
- https://github.com/AdoptOpenJDK/openjdk-jdk/pull/3

**Pull request closed without merging**
