### PR TITLE
Fix aarch32 jdk8 - use correct repo and JVM variant to enable JIT

### PR DESCRIPTION
**Pull request by sxa555**
Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/1257

Testing at https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-aarch32-jdk8/5

### CODE REVIEW

**Comment by sxa555** [comment]
LGTM - FYI @smlambert if we see any new test failures on JDK8/HotSpot/arm32 it may be because today's builds have a JIT enabled where they didn't previously now that this has been merged- will be good to keep a closer than usual eye on the results:

Previous build:
```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-202001071731-b05)
OpenJDK Zero VM (AdoptOpenJDK)(build 25.242-b05, interpreted mode)
```
Today's build:
```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-202001081353-b05)
OpenJDK Client VM (AdoptOpenJDK)(build 25.242-b05, mixed mode)
```

**Comment by smlambert** [comment]
Thanks for the heads up @sxa555 !

**Comment by MPavleski** [comment]
This is again broken, both the Deb package https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ and teh distributed file  OpenJDK8U-jdk_arm_linux_hotspot_8u252b09.tar.gz .

This is what I get from  OpenJDK8U-jdk_arm_linux_hotspot_8u252b09.tar.gz:

user@host:~/jdk8u252-b09/bin$ ./java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
OpenJDK Zero VM (AdoptOpenJDK)(build 25.252-b09, interpreted mode)

**Comment by sxa** [comment]
We never managed to successfully build the GA release from a branch with the JIT enabled, so it's not broken as such - it was never able to be released at a suitable stable level for us to be confident with it

Latest discussions were happening in https://github.com/AdoptOpenJDK/openjdk-tests/issues/1548

**Pull request merged**
