### PR TITLE
Do not default adopt_build_num to 1

### PR DESCRIPTION
**Pull request by johnoliver**

### CODE REVIEW

**Comment by gdams** [comment]
May also be worth updating https://github.com/AdoptOpenJDK/openjdk-build/blob/master/RELEASING.md in the same PR

**Comment by sxa** [comment]
When merge this fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/1696

**Comment by karianna** [comment]
`/home/jenkins/workspace/build-scripts-pr-tester/build-test/jobs/jdk11u/jdk11u-linux-x64-hotspot on build-softlayer-centos6-x64-1`

I assume that's a transient machine failure and we can merge this?

**Comment by johnoliver** [comment]
@gdams the advice in RELEASING.md looks correct, is there something you want adding?

**Comment by sxa** [comment]
@gdams Do you have any objects now? It's your request that's blocking approval on this

**Pull request merged**
