### PR TITLE
Fix #1934

### PR DESCRIPTION
**Pull request by douph1**
New try to fix broken #1934 and original #1834 has https://github.com/AdoptOpenJDK/openjdk-build/issues/1938 is merged

### CODE REVIEW

**Comment by douph1** [comment]
run tests

**Comment by douph1** [comment]
https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/openjdk-build-pr-tester/390/ and https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/openjdk-build-pr-tester/391/  success, no more error like
`Caused by: java.lang.ClassNotFoundException: ParseVersion`
wich was reverted by 
https://github.com/AdoptOpenJDK/openjdk-build/pull/1937

**Comment by douph1** [comment]
run tests

**Comment by douph1** [comment]
waiting status from https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/openjdk-build-pr-tester/398/

**Comment by douph1** [comment]
/job/build-scripts-pr-tester/job/openjdk-build-pr-tester/398/ was cancelled, retry

run tests

**Comment by karianna** [comment]
@douph1 - is this the latest Jenkins lib?  I'd like to reduce the number of security warnings.

I'm also concerned about the introduction of some of those licenses as we'd need to check that they're all APLv2 compatible.

**Comment by douph1** [comment]
> is this the latest Jenkins lib?

yes

> licence:

MIT
I'm not a legal team but ..
as we don't distribute, modify, or re-license the code I don't think the MIT licence is a problem

If you run the gradle build you will get all the deps .. and so you grab many licences that I have not checked and don't want to :

```
unzip -l  target/libs/adopt-shared-lib.jar  | grep -i license
     1172  2020-05-25 12:36   lib/hudson/thirdPartyLicenses_da.properties
     1202  2020-05-25 12:36   lib/hudson/thirdPartyLicenses_pt_BR.properties
     1153  2020-05-25 12:36   lib/hudson/thirdPartyLicenses_fr.properties
       84  2020-05-25 12:36   lib/hudson/thirdPartyLicenses_lt.properties
      100  2020-05-25 12:36   lib/hudson/thirdPartyLicenses_pt_PT.properties
      237  2020-05-25 12:36   lib/hudson/thirdPartyLicenses_uk.properties
     1178  2020-05-25 12:36   lib/hudson/thirdPartyLicenses_lv.properties
     2137  2020-05-25 12:36   lib/hudson/thirdPartyLicenses.jelly
     1235  2020-05-25 12:36   lib/hudson/thirdPartyLicenses_ru.properties
       81  2020-05-25 12:36   lib/hudson/thirdPartyLicenses_cs.properties
       96  2020-05-25 12:36   lib/hudson/thirdPartyLicenses_pl.properties
     1172  2020-05-25 12:36   lib/hudson/thirdPartyLicenses_de.properties
       79  2020-05-25 12:36   lib/hudson/thirdPartyLicenses_hu.properties
     1172  2020-05-25 12:36   lib/hudson/thirdPartyLicenses_sv_SE.properties
       94  2020-05-25 12:36   lib/hudson/thirdPartyLicenses_it.properties
     1347  2020-05-25 12:36   lib/hudson/thirdPartyLicenses_bg.properties
     1185  2020-05-25 12:36   lib/hudson/thirdPartyLicenses_he.properties
      100  2020-05-25 12:36   lib/hudson/thirdPartyLicenses_ko.properties
     1183  2020-05-25 12:36   lib/hudson/thirdPartyLicenses_es.properties
     1180  2020-05-25 12:36   lib/hudson/thirdPartyLicenses_fi.properties
     1194  2020-05-25 12:36   lib/hudson/thirdPartyLicenses_ja.properties
      232  2020-05-25 12:36   lib/hudson/thirdPartyLicenses_sr.properties
       76  2020-05-25 12:36   lib/hudson/thirdPartyLicenses_sk.properties
     1155  2020-05-25 12:36   lib/hudson/thirdPartyLicenses_nl.properties
     1172  2020-05-25 12:36   lib/hudson/thirdPartyLicenses_nb_NO.properties
     1186  2020-05-25 12:36   lib/hudson/thirdPartyLicenses_zh_TW.properties
     1323  2020-05-25 12:36   hudson/PluginWrapper/thirdPartyLicenses_pt.properties
     1332  2020-05-25 12:36   hudson/PluginWrapper/thirdPartyLicenses_pt_BR.properties
       83  2020-05-25 12:36   hudson/PluginWrapper/thirdPartyLicenses_fr.properties
       15  2020-05-25 12:36   hudson/PluginWrapper/thirdPartyLicenses_lt.properties
     1900  2020-05-25 12:36   hudson/PluginWrapper/thirdPartyLicenses.jelly
      127  2020-05-25 12:36   hudson/PluginWrapper/thirdPartyLicenses_ru.properties
     1216  2020-05-25 12:36   hudson/PluginWrapper/thirdPartyLicenses_pl.properties
     1270  2020-05-25 12:36   hudson/PluginWrapper/thirdPartyLicenses_de.properties
     1317  2020-05-25 12:36   hudson/PluginWrapper/thirdPartyLicenses_it.properties
     1588  2020-05-25 12:36   hudson/PluginWrapper/thirdPartyLicenses_bg.properties
     1320  2020-05-25 12:36   hudson/PluginWrapper/thirdPartyLicenses_es.properties
     1315  2020-05-25 12:36   hudson/PluginWrapper/thirdPartyLicenses_ja.properties
      437  2020-05-25 12:36   hudson/PluginWrapper/thirdPartyLicenses_sr.properties
       15  2020-05-25 12:36   hudson/PluginWrapper/thirdPartyLicenses.properties
     1303  2020-05-25 12:36   hudson/PluginWrapper/thirdPartyLicenses_zh_TW.properties
    11358  2020-05-18 20:00   META-INF/LICENSE
        0  2020-06-30 09:15   META-INF/licenses/
     1639  2020-05-18 20:00   META-INF/licenses/antlr2-license.txt
     1508  2020-05-18 20:00   META-INF/licenses/antlr4-license.txt
     1588  2020-05-18 20:00   META-INF/licenses/asm-license.txt
     1084  2016-01-31 08:16   LICENSE
    11359  2017-10-15 11:58   META-INF/LICENSE.txt
     1113  2014-04-13 12:57   org/kohsuke/stapler/codemirror/mode/vb/LICENSE.txt
     1226  2014-04-13 12:57   org/kohsuke/stapler/codemirror/mode/sieve/LICENSE
     1109  2014-04-13 12:57   org/kohsuke/stapler/codemirror/mode/xquery/LICENSE
     1094  2014-04-13 12:57   org/kohsuke/stapler/codemirror/mode/perl/LICENSE
     1078  2014-04-13 12:57   org/kohsuke/stapler/codemirror/mode/pascal/LICENSE
     1075  2014-04-13 12:57   org/kohsuke/stapler/codemirror/mode/python/LICENSE.txt
     1487  2014-04-13 12:57   org/kohsuke/stapler/codemirror/mode/ruby/LICENSE
     1151  2014-04-13 12:57   org/kohsuke/stapler/codemirror/mode/coffeescript/LICENSE
     1486  2014-04-13 12:57   org/kohsuke/stapler/codemirror/mode/r/LICENSE
    11357  2011-09-09 08:53   META-INF/license.txt
    35084  2019-08-19 02:20   LICENSE.md
    11376  2020-01-01 16:44   LICENSE-junit.txt
      316  2018-04-13 20:35   META-INF/LICENSE-notice.md
    14235  2020-02-15 16:08   META-INF/LICENSE.md
     1509  2012-07-09 20:49   LICENSE.txt
        0  2020-06-30 09:15   license/
     3998  2003-11-18 15:19   license/LICENSE.dom-documentation.txt
     3522  2003-11-18 15:19   license/LICENSE.dom-software.txt
      782  2003-11-18 15:19   license/LICENSE.sax.txt
     1242  2003-11-18 15:19   license/README.dom.txt
      691  2003-11-18 15:19   license/README.sax.txt
     2592  2004-02-27 13:39   BCEL.LICENSE.txt
     1149  2004-02-27 13:39   java_cup.LICENSE.txt
     2592  2004-02-27 13:39   regexp.LICENSE.txt
     1174  2004-02-27 13:39   runtime.LICENSE.txt
```


So forget adding this jenkins-core, I will do another PR with vanilla groovy code

**Pull request closed without merging**
