### PR TITLE
Fix #1934

### PR DESCRIPTION
**Pull request by douph1**
same as current jenkins version : 2.222.4 

fix can be tested with
openjdk-build/pipelines$ `./gradlew clean uberJar`

### CODE REVIEW

**Comment by M-Davies** [comment]
run tests

**Comment by douph1** [comment]
@M-Davies ok to squash-merge ?
what about `run tests` ?

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
PR tester failures look unrelated. LGTM for me

**Pull request merged**
