### PR TITLE
actions: disable macOS PR tester

### PR DESCRIPTION
**Pull request by gdams**
to help free up builds

### CODE REVIEW

**Review by aahlenst — APPROVED** [review]
I just close my eyes and weep inside :see_no_evil:

**Review by sxa — APPROVED** [review]
Approved, assuming george will verify it once merged ;-)

**Comment by karianna** [comment]
@gdams Are we enabling this later?

**Comment by aahlenst** [comment]
@karianna There aren't enough macOS workers to keep up with the work. Having to wait >12 hours isn't tenable. So either we add more workers (tough as long as GitHub Actions does not support stateless custom runners) or we come up with a chatbot or something like that that allows us to run the tests only when needed and hereby decrease the load on the available workers.

**Comment by karianna** [comment]
How do we add more workers?

**Comment by aahlenst** [comment]
We cannot at the moment. The problem is https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories and no support for self-hosted elastic agent pools. So either you make one of your magic phone calls (or emails, mind control, or whatever you do in such situations 😁) to increase our allowance (GitHub supposedly uses Orka) or we have to use another CI system. Haven't heard yet from CircleCI. I don't know whether we could use our Jenkins. AppVeyor Server can do all those things (I use it at work), but that would be a separate infra and a lot of work.

**Pull request merged**
