### PR TITLE
Add triggers for external_extended tests

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Add triggers for external_extended tests
Signed-off-by: Mesbah <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
@smlambert - could you please merge this PR?

**Comment by karianna** [comment]
Note to self - port this to the `new_build_scripts`

**Comment by karianna** [comment]
Ported locally.

**Comment by smlambert** [comment]
Thanks @Mesbah-Alam 

Note that this new set of extended tests is comprised of the microprofile tcks.

**Pull request merged**
