### PR TITLE
Update CA certificates

### PR DESCRIPTION
**Pull request by aahlenst**
Most significant change: 10 old Symantec root certificates were removed as part of the general distrust of Symantec root certificates.

https://bugzilla.mozilla.org/show_bug.cgi?id=1670769

Full changes of generated cacerts trust store:

```
Removed CA certificates: 10
c=us,o=geotrust inc.,cn=geotrust primary certification authority
37d51006c512eaab626421f1ec8c92013fc5f82ae98ee533eb4619b8deb4d06c
c=us,o=thawte, inc.,ou=certification services division,ou=(c) 2008 thawte, inc. - for authorized use only,cn=thawte primary root ca - g3
4b03f45807ad70f21bfc2cae71c9fde4604c064cf5ffb686bae5dbaad7fdd34c
c=us,o=verisign, inc.,ou=verisign trust network,ou=(c) 2007 verisign, inc. - for authorized use only,cn=verisign class 3 public primary certification authority - g4
69ddd7ea90bb57c93e135dc85ea6fcd5480b603239bdc454fc758b2a26cf7f79
c=us,o=thawte, inc.,ou=certification services division,ou=(c) 2006 thawte, inc. - for authorized use only,cn=thawte primary root ca
8d722f81a9c113c0791df136a2966db26c950a971db46b4199f4ea54b78bfb9f
c=us,o=verisign, inc.,ou=verisign trust network,ou=(c) 2006 verisign, inc. - for authorized use only,cn=verisign class 3 public primary certification authority - g5
9acfab7e43c8d880d06b262a94deeee4b4659989c3d0caf19baf6405e41ab7df
c=us,o=geotrust inc.,cn=geotrust universal ca 2
a0234f3bc8527ca5628eec81ad5d69895da5680dc91d1cb8477f33f878b95b0b
c=us,o=geotrust inc.,cn=geotrust universal ca
a0459b9f63b22559f5fa5d4c6db3f9f72ff19342033578f073bf1d1b46cbb912
c=us,o=thawte, inc.,ou=(c) 2007 thawte, inc. - for authorized use only,cn=thawte primary root ca - g2
a4310d50af18a6447190372a86afaf8b951ffb431d837f1e5688b45971ed1557
c=us,o=geotrust inc.,ou=(c) 2008 geotrust inc. - for authorized use only,cn=geotrust primary certification authority - g3
b478b812250df878635c2aa7ec7d155eaa625ee82916e2cd294361886cd1fbd4
c=us,o=geotrust inc.,cn=geotrust global ca
ff856a2d251dcd88d36656f450126798cfabaade40799c722de4d2b5db36a73a

Added CA certificates: 1
subject=c = kr, o = naver business platform corp., cn = naver global root certification authority
88f438dcf8ffd1fa8f429115ffe5f82ae1e06e0c70c375faad717b34a49e7265
```

### CODE REVIEW

**Comment by aahlenst** [comment]
In case someone wonders why the there are more changes in certdata.txt than in the effective trust store: Expired certificates are automatically filtered out when generating the trust store.

**Comment by M-Davies** [comment]
Does this fix #2433 ?

**Comment by aahlenst** [comment]
@M-Davies Not necessarily. Maybe there's another update until then. Not very likely, but still.

**Comment by M-Davies** [comment]
run tests

**Review by karianna — APPROVED** [review]
LGTM

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
run tests.

**Comment by M-Davies** [comment]
run tests

**Review by M-Davies — APPROVED** [review]

**Pull request merged**
