### PR TITLE
Use chronological tag sorting to get latest version tag

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Signed-off-by: Andrew Leonard <andrew_m_leonard@uk.ibm.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/2050

The problem with the current get latest tag logic is it will not work on shallow clone (--depth=1) as the whole local repo is depth=1 so there is no "topo-order". You also cannot rely on commit timestamp, as they are not chronogloical eg.a 3 month old commit can be merged today and it's timestamp will be 3 months ago, and if that is tagged then that tag will be 3 months old even if it is the latest build tag.

With OpenJ9 we fixed this by simply querying all the tags for the version in question and doing a chronological sort, I have applied the same logic for Hotspot in sbin.build.sh.

**Comment by austin0** [comment]
run tests

**Comment by M-Davies** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
Subject to the known issues with nightly builds, the PR test jobs look good.

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
run tests

**Review by karianna — COMMENTED** [review]
Bravo on the comments in this code!  I'll need @johnoliver or @gdams to comment on this as my spidey sense tells me this was historically fragile.

**Comment by karianna** [comment]
@gdams or @johnoliver - this is a good PR but I'm nervous of this area - could do with your review given historical context

**Review by johnoliver — APPROVED** [review]

**Review by karianna — APPROVED** [review]

**Review by gdams — APPROVED** [review]

**Pull request merged**
