### PR TITLE
Always pre-clean workspace on mac

### PR DESCRIPTION
**Pull request by M-Davies**
Fixes: #1980 
Signed-off-by: Morgan Davies <morgan.davies@ibm.com>

### CODE REVIEW

**Comment by M-Davies** [comment]
Groovy compile error should not be due to these changes. Moving into review readiness

**Comment by M-Davies** [comment]
https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/openjdk-build-pr-tester/503/console tests this on mac

**Comment by M-Davies** [comment]
> is there something in the code that's forcing AIX to do the same?

I haven't seen AIX produce the error seen in #1980 . @adamfarley @andrew-m-leonard have you?

**Comment by karianna** [comment]
> Seems a bit of a shame to do this as it means we are unable to update from an existing clone on the repo, requiring us to clone each time :-(
> 
> Related - is there something in the code that's forcing AIX to do the same? We were using a ramdisk previously but are not any more so it would be good to disable cleaning (probably post-cleaning thinking about it) on AIX if possible. I couldn't find where it was being done despite playing with a few options :-)

It would be good to know why it fails...

**Comment by karianna** [comment]
I think you need to rebase to get that Groovy compile bug gone.

**Comment by M-Davies** [comment]
> I think you need to rebase to get that Groovy compile bug gone.

Done

**Pull request merged**
