### PR TITLE
Extract freetype font param into makejdk any platform script

### LINKED ISSUE #51: Further refactoring on build script for eliminating platform specific settings
On the back of the PR https://github.com/AdoptOpenJDK/openjdk-build/pull/50 we discussed that we want to be able to build OpenJDK outside Jenkins so the same script should be usable for both local machine and jenkins build.

### PR DESCRIPTION
**Pull request by neomatrix369**
Moved the FREETYPE_FONT_BUILD_TYPE_PARAM setting from inside build.sh to makejdk-any-platform.sh, used = instead of - when checking and setting for default value to FREETYPE_FONT_BUILD_TYPE_PARAM in makejdk-any-platform.sh

Finally fixes #51 fully.

### CODE REVIEW

**Comment by neomatrix369** [comment]
Kicked off a ppc build at https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk_build_ppc64le_linux_mani_test/1/console and picked up from the logs - works: 
`cd builds/unix; ./configure  '--prefix=/home/jenkins/workspace/openjdk_build_ppc64le_linux_mani_test/openjdk/installedfreetype' '--build=powerpc64le-redhat-linux-gnu'`

**Comment by neomatrix369** [comment]
When this is merged we can happily close #51. And also tidy up all our jenkins jobs, remove parameters that are not needed.

**Comment by karianna** [comment]
@neomatrix369 Merge conflicts.

**Comment by neomatrix369** [comment]
Conflicts resolved.

**Pull request merged**
