### PR TITLE
remove unused docker build stuff

### PR DESCRIPTION
**Pull request by gdams**
We no longer use these docker scripts as all the new scripts are now in https://github.com/AdoptOpenJDK/openjdk-docker

### CODE REVIEW

**Comment by karianna** [comment]
@neomatrix369 Can you sanity check that openjdk-docker supersedes this?

**Comment by neomatrix369** [comment]
I'm only raising a discussion as the bash scripts and `Dockerfile` in `openjdk-docker` repo might not be doing exactly how we had initially agreed to do the steps to produce a docker image when it was accepted in this repo  - I could be wrong but worth ask https://github.com/dinogun (@dinogun) or anyone else who have been involved. 

Will hate to loose out on the original knowledge in this repo if its helpful / useful wrt building Docker images and pushing them to Docker hub.

**Comment by neomatrix369** [comment]
When I get a chance, hopefully soon, I could try running the scripts in the `openjdk-docker` repo and see if I can progress with it, and also see if I can salvage the original ideas from the scripts in this repo and transfer it to the `openjdk-docker` repo.

**Comment by karianna** [comment]
@spoole167, @dinogun, @neomatrix369 can you finalise the code move (if any is required)? I'd like to merge this PR :-)

**Comment by neomatrix369** [comment]
From my previous observations, the scripts are different and its best to retain our scripts that build OpenJDK in the docker environment, @dinogun's scripts do a bit more, i.e. push the images to docker hub. I still feel they are orthogonal processes.

**Comment by gdams** [comment]
@neomatrix369 these scripts have nothing to do with the building openjdk in a docker environment. The scripts that I have removed in this PR remove a previous attempt of what @dinogun's new scripts do. We will still be able to build openjdk in a docker based environment (this PR removes the code that was used to create docker containers with openjdk pre installed in)

**Comment by karianna** [comment]
I'll merge this, git history will still have the code so we can always port that across if anything is lacking

**Pull request merged**
