### PR TITLE
Set GRADLE_USER_HOME to workspace/.gradle

### PR DESCRIPTION
**Pull request by M-Davies**
Closes: #991 
Signed-off-by: Morgan Davies <morgan.davies@ibm.com>

### CODE REVIEW

**Comment by M-Davies** [comment]
Testing at https://ci.adoptopenjdk.net/view/work%20in%20progress/job/jdk15-mac-x64-hotspot/6/console shows gradle builds but I can't verify if gradle was actually built there. @sxa Can you log onto the machine (`build-macstadium-macos1014-x64-1 `) and verify that gradle upheld the path that was declared in `GRADLE_USER_HOME`?

**Comment by M-Davies** [comment]
run tests

**Comment by karianna** [comment]
Setting status of e3cf6df538cd1dedb4d7f7ac3954df209e8464f4 to FAILURE with url https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/openjdk-build-pr-tester/339/ and message: 'Build finished. '
Using context: pipeline-build-check
java.nio.file.NoSuchFileException: /home/jenkins/.jenkins/workspace/build-scripts-pr-tester/openjdk-build-pr-tester/pipelines/jobs/configurations/jdk8_pipeline_config.groovy

**Comment by M-Davies** [comment]
> Setting status of [e3cf6df](https://github.com/AdoptOpenJDK/openjdk-build/commit/e3cf6df538cd1dedb4d7f7ac3954df209e8464f4) to FAILURE with url https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/openjdk-build-pr-tester/339/ and message: 'Build finished. '
> Using context: pipeline-build-check
> java.nio.file.NoSuchFileException: /home/jenkins/.jenkins/workspace/build-scripts-pr-tester/openjdk-build-pr-tester/pipelines/jobs/configurations/jdk8_pipeline_config.groovy

Not related to this. PR tester is going to be fixed in https://github.com/AdoptOpenJDK/openjdk-build/pull/1919

**Pull request merged**
