### PR TITLE
bump jdk8u hotspot builds to win2012

### PR DESCRIPTION
**Pull request by gdams**
FYI @sxa555 this will allow us to destroy the 2008 machines and provision more 2012 build machines

### CODE REVIEW

**Comment by gdams** [comment]
test builds:

jdk8u-windows-x86-32 (https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x86-32-hotspot/529/)

**Comment by aahlenst** [comment]
If this gets merged, do we need to change the support statement on the website to "Windows Server 2012 or newer" instead of "Windows 2008r2 or later"?

**Comment by gdams** [comment]
@aahlenst we probably should even though we won't be breaking backwards compatibility because it's built on the same toolchain version

**Comment by gdams** [comment]
run tests

**Comment by karianna** [comment]
> @aahlenst we probably should even though we won't be breaking backwards compatibility because it's built on the same toolchain version

I'd actually state the opposite.  We should probably make it clear what we build on vs what we can support on.

**Comment by karianna** [comment]
`Execution error: No such property: versionInfo for class: Build`

**Comment by gdams** [comment]
@karianna this PR checker has been broken by the recent Pipeline changes that allow the jobs to run in parallel, that particular failure has actually come from my other PR here: https://github.com/AdoptOpenJDK/openjdk-build/pull/1639

This PR is good to go (see the two test builds at the top)

**Pull request merged**
