### PR TITLE
Add flag to enable/disable installers

### PR DESCRIPTION
**Pull request by M-Davies**
Unlike the recent dockerExcludes param, this new param gets passed down to the downsteam build job (hence the extra additions to the config files)

Closes: #2011
Signed-off-by: Morgan Davies <morgan.davies@ibm.com>

### CODE REVIEW

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
Installers all failed due to the [current nightly build](https://docs.google.com/document/d/1vcZgHJeR8rW8U8OD23Uob7A1dbLrtkURZUkinUp7f_w/edit#heading=h.nedv5p357hmm) problems that we've been having. The following jobs test this PR with `ENABLE_INSTALLERS` set as false:
- https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk8u/job/jdk8u-windows-x64-hotspot/14/console
- https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk11u/job/jdk11u-mac-x64-hotspot/39/console

**Comment by M-Davies** [comment]
`ENABLE_INSTALLERS` worked. The installers weren't run on either of the linked builds above. Signing jobs ran but that's an altogether different parameter to add. This is Ready for review

**Comment by karianna** [comment]
@M-Davies - The test build failed but the result is not lost to time.  So I'll run tests again

**Comment by karianna** [comment]
run tests

**Comment by karianna** [comment]
hmm, looks like Jenkins is not having a good time here

**Comment by karianna** [comment]
run tests

**Comment by M-Davies** [comment]
@karianna What's the problem with this PR? The PR-tester is failing due to the current nightly build problems [identified yesterday](https://docs.google.com/document/d/1vcZgHJeR8rW8U8OD23Uob7A1dbLrtkURZUkinUp7f_w/edit#heading=h.nedv5p357hmm)

**Comment by sxa** [comment]
@M-Davies I assume this will affect Linux, Windows and macos install jobs?

**Comment by karianna** [comment]
> @karianna What's the problem with this PR? The PR-tester is failing due to the current nightly build problems [identified yesterday](https://docs.google.com/document/d/1vcZgHJeR8rW8U8OD23Uob7A1dbLrtkURZUkinUp7f_w/edit#heading=h.nedv5p357hmm)

Yeah it's just the PR tester failing so we can land this.

**Comment by M-Davies** [comment]
@sxa Correct

**Pull request merged**
