### PR TITLE
Refactor makejdk script

### PR DESCRIPTION
**Pull request by neomatrix369**
- Refactored blocks of bash code in makejdk.sh into respective bash functions...
- Added default values to global variables used across the script
- Corrected boolean comparisons - wrapped them around quotes, fixed issue...
- Added {} braces around a number of variables within double quotes

### CODE REVIEW

**Comment by neomatrix369** [comment]
Kicked off a build - https://ci.adoptopenjdk.net/job/openjdk_build_x86-64_linux_mani_test/4/console and seems go thru fine without any issues

**Comment by neomatrix369** [comment]
Build finished successfully.

**Comment by karianna** [comment]
@neomatrix369 I merged #40 so you'll have to resolved conflicts and push again sorry!

**Comment by neomatrix369** [comment]
Thanks @karianna 
@Bluevisitor I have eye-balled https://github.com/AdoptOpenJDK/openjdk-build/pull/40 to see if I haven't overridden any of your changes, but feel free to look at it for yourself to see if that is the case too.

If we all missed it, the build system will catch us anyways - but dont want to leave it to that late.

**Pull request merged**
