### PR TITLE
Extra arguments for jtreg execution

### PR DESCRIPTION
**Pull request by Bluevisitor**
The original plan for this branch was to add a series of options onto the jtreg command line.

However, the debug output from an earlier job shows us that these options are all used by default.

In the process of learning this, I discovered that there appears to be a variable defined entirely for the purpose of allowing the user to set jtreg command-line options without having to directly edit the makefile (which is what we used to do, using sed).

So now I'm moving us from sed to this environment variable.

### CODE REVIEW

**Comment by Bluevisitor** [comment]
Make documentation appears to imply that a variable passed into a makefile via an environment variable can be manipulated internally, unlike command-line arguments.

If that is the case, the test here should have the concurrency setting for jtreg set explicitly to 2. 

https://ci.adoptopenjdk.net/job/adam_test/6/

If this is not the case, the concurrency variable will not be explicitly set to 2, and we'll need to add -concurrency:2 to the EXTRA_JTREG_OPTIONS environment variable consumed by the makefile.

**Comment by neomatrix369** [comment]
@Bluevisitor Changes look fine although https://ci.adoptopenjdk.net/job/adam_test/6/console show test run has broken

**Comment by Bluevisitor** [comment]
I see 2 points for concern:

1) The test fails due to the 2 concurrency options on the jtreg command line. 
2) The concurrency option used to be set to "7", despite the fact that we were setting it to 8. Now it's still setting the concurrency option (both of them) to 7, despite the fact that I changed it to 2 in the environment variable.

Will investigate.

**Comment by Bluevisitor** [comment]
The 2 concurrency options may be caused by bug: https://bugs.openjdk.java.net/browse/JDK-8157605

It's fixed in jdk9, but the request to backport is to 8 has gone unanswered. Also had difficulty finding why/how it takes the concurrency value and subtracts from it before passing the final value to the jtreg command.

Right now, my best plan is to replace the concurrency environment variable with a direct -concurrency option inside the EXTRA_JTREG_OPTIONS variable.

**Comment by Bluevisitor** [comment]
Here's a jenkins run to test that the aforementioned change works: https://ci.adoptopenjdk.net/job/adam_test/7/

**Comment by Bluevisitor** [comment]
Didn't work. Will investigate further.

**Comment by gdams** [comment]
with regard to `3` we probably don't want the test to fail if no tests are found otherwise it will fail every time we build without the `--jtreg` flag

**Comment by Bluevisitor** [comment]
It seems the only way around this is to get the fix for the bug (link below) backported to jdk8. Will raise a new bug to cover this.

https://bugs.openjdk.java.net/browse/JDK-8157605

As for this PR, the only change we can make now is the change to the jenkins job config to cause a job failure if there are no results files. Since that doesn't need a PR, I'm removing this PR and deleting the branch.

**Comment by Bluevisitor** [comment]
Sorry George, I didn't spot your comment. Will leave the jenkins option alone.

**Pull request closed without merging**
