### PR TITLE
Build freetype font library via an external script

### PR DESCRIPTION
**Pull request by neomatrix369**
Further development work, on the back of the PR #117

Conversation history on https://github.com/AdoptOpenJDK/openjdk-build/pull/141, closed due to issues with some changes made not reflected in the PR

### CODE REVIEW

**Comment by neomatrix369** [comment]
TravisCI is showing warning/errors on lines across script files not changed by this PR

**Comment by neomatrix369** [comment]
@gdams Here's my question https://github.com/AdoptOpenJDK/openjdk-build/pull/141#issuecomment-313691236 in response to your comment https://github.com/AdoptOpenJDK/openjdk-build/pull/141#issuecomment-313038161

**Comment by karianna** [comment]
Does this cover Windows?  Also Travis fails.

**Comment by neomatrix369** [comment]
Same issue with TravisCI - changes pointed out are not part of this PR.

Works on windows - as per the Pipeline PR job https://ci.adoptopenjdk.net/job/openjdk_pr_x86-64_windows/37/consoleFull

**Comment by neomatrix369** [comment]
@gdams Do you have anything else on this PR, can I pls merge it? As you can see from the scripts, the code function `buildFreeTypeFontLibrary()` is used by both our current build scripts `common-functions.sh` and also by `setupFreeTypeFontLibrary.sh`. The PR build pipeline ran it across all platforms so we are sound there.

Can I please request you to test `setupFreeTypeFontLibrary.sh` out on a Windows platform and a non-Windows platform the way you had envisioned to use it and give me some feedback, I can amend the script accordingly?

**Comment by neomatrix369** [comment]
@karianna do you have anything else to be done with this PR, after my comments from above?

**Comment by neomatrix369** [comment]
@bblondin can you please give the above a whirl on Windows and non-Windows system to see if it works for you the way @gdams has envisioned it to work. When done can you (both) please give me feedback here so I can amend the PR or respond with my views. Thanks chaps!

**Comment by karianna** [comment]
@neomatrix369 Did you mean to close this as opposed to merging it?

**Comment by neomatrix369** [comment]
I actually didn't mean to close this PR, I must have accidentally deleted the branch while cleaning up stale branches and that caused this PR to close.

**Comment by karianna** [comment]
OK I'll let them merge when complete.

**Comment by neomatrix369** [comment]
@karianna yeah thought that would be the best, over to the great chaps from BigBlue - IBM, ia, ia, Watson. ;)

**Comment by neomatrix369** [comment]
@bblondin @gdams still open, need any help here to push this forward?

**Comment by karianna** [comment]
@neomatrix369 Can you rebase again please?  There's a readme conflict

**Comment by neomatrix369** [comment]
I suggest closing this PR, it's quite old and the implementation in it is most likely not needed anymore. Worth focussing our efforts on other things.

**Pull request closed without merging**
