### PR TITLE
Shallow git clone

### PR DESCRIPTION
**Pull request by neomatrix369**
To speed up cloning of openjdk repo on local env and VMs

### CODE REVIEW

**Comment by gdams** [comment]
@neomatrix369 does this enable shallow clone by default ? or do you have to specify it?

**Comment by neomatrix369** [comment]
@gdams shallow clones by default, git flag is set in the header of the script

**Comment by gdams** [comment]
okay I would argue that we should not shallow clone by default. My reason being that the idea of makejdk.sh is that you can clone the git repo and then make changes and then test builds. If we don't clone the git history in by default it will make creating Pull Requests much harder. CC @tellison for his opinion here.

**Comment by neomatrix369** [comment]
I can make this into an environment variable but then we will have to manually set it up in each environment or in your ansible scripts - is that okay? by default it will be blank once I change it - works for you?

**Comment by gdams** [comment]
can we not just make it a command line variable ?

**Comment by neomatrix369** [comment]
@gdams thats another way to make it available - lets see what I can do

**Comment by karianna** [comment]
@neomatrix369 Is there more for you to do on this?

**Comment by neomatrix369** [comment]
@karianna @gdams and I are discussing what the default value if this option (git shallow) should be and whether to use a cmd-line arg. or env. variable to set this value.

**Comment by neomatrix369** [comment]
My thoughts here are:
- by default always have shallow git clone (due to low usage always cloning shallow is harmless)
- override this setting via a command-line switch --disable-shallow-git-clone (although I would prefer an environment variable but due to low usage command-line switch is good, cmd-line switch is fine too, but if number of scripts increases then env variable would be a better choice. As amending multiple script to maintain consistency and check for flag, etc... can become tedious with cmd-line switch)

I'll send out an updated PR soon.

**Comment by neomatrix369** [comment]
@gdams just about doing that :+1:

**Comment by neomatrix369** [comment]
Also kicked off https://ci.adoptopenjdk.net/view/OpenJDK%20PR/job/openjdk_pr_pipeline/8/console with git shallow clone option enabled

**Pull request merged**
