### PR TITLE
add always incase of missing tag name

### PR DESCRIPTION
**Pull request by karianna**

### CODE REVIEW

**Comment by neomatrix369** [comment]
@karianna Ran it via any pipeline jobs?

**Comment by karianna** [comment]
Not yet - @gdams you mentioned you'd set up generic jobs to run PRs like this one.  Which job(s) on CI is that?

**Comment by gdams** [comment]
https://ci.adoptopenjdk.net/view/OpenJDK%20PR/job/openjdk_pr_pipeline/

**Comment by gdams** [comment]
I'll kick off a run

**Comment by gdams** [comment]
https://ci.adoptopenjdk.net/view/OpenJDK%20PR/job/openjdk_pr_pipeline/10/console

**Comment by karianna** [comment]
Hmm, the version checking function doesn't even seem to get called on these builds...   Can't understand why this diff / patch would stop the function be called.

**Pull request merged**
