### PR TITLE
Add ADDITIONAL_TEST_LABEL to allow targeting variant test jobs appropriately

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Allow additional test labels, for example jdk15+ openj9 cannot run on centos6 or rhel6.

Signed-off-by: Andrew Leonard <anleonar@redhat.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
test with new config: https://ci.adoptopenjdk.net/view/all/job/build-scripts-testing/job/jobs/job/jdk15u/job/jdk15u-linux-x64-openj9/2/

**Comment by andrew-m-leonard** [comment]
Fixes https://github.com/AdoptOpenJDK/openjdk-build/issues/2373

**Review by karianna — APPROVED** [review]
LGTM but please check failing builds

**Comment by andrew-m-leonard** [comment]
@karianna The failed build was a known build break for openj9, I think they've fixed it now, so re-freshing this, should be good now

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
Code looks good but I'll wait for the PR tester to finish before reviewing

**Comment by sxa** [comment]
> @karianna The failed build was a known build break for openj9, I think they've fixed it now, so re-freshing this, should be good now

There seems to be failures with JDK11/hotspot and alpine too though

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
run tests

**Review by sxa — APPROVED** [review]
Since Morgan was ok with this as log as the pipelines pass I reckon I am too (I'm assuming the new label conditional is syntactically correct!) - let's keep an eye on it and make sure there are no problems as we need stability this week.

**Review by M-Davies — APPROVED** [review]
@andrew-m-leonard So long as you're happy that the PR is producing the parameter as you expect, this looks good to me 👍

**Comment by andrew-m-leonard** [comment]
Running a test jdk15 x/pLinux pipeline: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk15-pipeline/439/

**Pull request merged**
