### PR TITLE
Make Changes to Allow Jenkins to Parse Jtreg Test Results

### PR DESCRIPTION
**Pull request by Bluevisitor**
Right now the plan seems to be:

- Make the xml results (from the jtreg run) visible.
- Get Jenkins to parse it.
- Make sure Jenkins lists the job as "failed" when the tests fail.

### CODE REVIEW

**Comment by gdams** [comment]
```
Test Results

Summary reports are generated in the report directory, in plain text and HTML formats. To generate a detailed report in XML as well, use the -xml option.

    The plain text report in report-dir/text/summary.txt contains one test result per line and is well suited for processing with tools like grep.
    The XML report can be used with CI systems like Hudson to generate trend graphs. See Regression Test Harness and Hudson Continuous Integration System on how to do this.
```

**Comment by gdams** [comment]
looks like our jtreg runs should already support this

**Comment by Bluevisitor** [comment]
Thanks gdams. I'm working my way through the instructions.

http://openjdk.java.net/jtreg/jtreg-hudson.html

**Comment by neomatrix369** [comment]
@Bluevisitor Its a good practise to close this PR and reopen it when its ready to be reviewed and merged - filters out the active PRs we need to review asap. thnx

**Comment by gdams** [comment]
@neomatrix369 I have added the `WIP` tag. This means that the PR is a work in progress and not ready to be reviewed. I would leave it open so that we can discuss

**Comment by Bluevisitor** [comment]
The basics seem to work: https://ci.adoptopenjdk.net/job/adam_test/2/

After speaking with Mani and George, we agreed that this is a good opportunity to switch over to using our home-grown jtreg. Will alter the URL as we've discussed.

**Comment by Bluevisitor** [comment]
Here's a test run to make sure it works: https://ci.adoptopenjdk.net/job/adam_test/5/

And the next commit will be my removal of the space I put in a readme file in order to create this PR.

**Pull request merged**
