### PR TITLE
update bisheng source repo and tag search rules

### PR DESCRIPTION
**Pull request by feilongjiang**
Change bisheng source code repo to the official [OpenEuler mirror](https://github.com/openeuler-mirror/bishengjdk-11) and update tag search rules.

### CODE REVIEW

**Review by karianna — APPROVED** [review]
LGTM

**Review by M-Davies — APPROVED** [review]

**Comment by feilongjiang** [comment]
I'm not authorized to merge this pull request, can someone merge this?

**Comment by sxa** [comment]
I've verified that this change is good and it builds successfully.

@feilongjiang We are currently running through a release cycle for JDK16 so have frozen all non-critical changes going into the build repositories. Are you happy to wait for this change to go in until later next week?

**Comment by feilongjiang** [comment]
> Are you happy to wait for this change to go in until later next week?

No problem.

**Pull request merged**
