### PR TITLE
Enable arch ppc64 for smoke tests

### PR DESCRIPTION
**Pull request by sophia-guo**
Enable arch ppc64 for smoke tests

related https://github.com/adoptium/ci-jenkins-pipelines/issues/127

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Fix the failure:

```
13:58:01  Caused by: java.lang.AssertionError: Unrecognized architecture: ppc64
13:58:01  	at net.adoptopenjdk.test.JdkPlatform.detectArchitecture(JdkPlatform.java:90)
```
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-hotspot_SmokeTests/1/console

after fix:
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-hotspot_SmokeTests/2/console, which is related with #2567

**Review by smlambert — APPROVED** [review]
thanks @sophia-guo !

**Comment by M-Davies** [comment]
Linter issues (I realise they are not related to your changes but it would be good to get them fixed regardless 🙂)
```
Starting audit...
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:1: File does not end with a newline. [NewlineAtEndOfFile]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:1: Missing package-info.java file. [JavadocPackage]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:22:5: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:24:5: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:26:5: Missing a Javadoc comment. [MissingJavadocMethod]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:31:5: Class 'JdkPlatform' looks like designed for extension (can be subclassed), but the method 'runsOn' does not have javadoc that explains how to do that safely. If class is not designed for extension consider making the class 'JdkPlatform' final or making the method 'runsOn' static/final/abstract/empty, or adding allowed annotation for the method. [DesignForExtension]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:31:5: Missing a Javadoc comment. [MissingJavadocMethod]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:31:27: Parameter architecture should be final. [FinalParameters]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:31:40: 'architecture' hides a field. [HiddenField]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:35: Line is longer than 80 characters (found 82). [LineLength]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:35:5: Class 'JdkPlatform' looks like designed for extension (can be subclassed), but the method 'runsOnAnyArchitecture' does not have javadoc that explains how to do that safely. If class is not designed for extension consider making the class 'JdkPlatform' final or making the method 'runsOnAnyArchitecture' static/final/abstract/empty, or adding allowed annotation for the method. [DesignForExtension]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:35:5: Missing a Javadoc comment. [MissingJavadocMethod]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:35:42: Parameter architectures should be final. [FinalParameters]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:39:5: Class 'JdkPlatform' looks like designed for extension (can be subclassed), but the method 'runsOn' does not have javadoc that explains how to do that safely. If class is not designed for extension consider making the class 'JdkPlatform' final or making the method 'runsOn' static/final/abstract/empty, or adding allowed annotation for the method. [DesignForExtension]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:39:5: Missing a Javadoc comment. [MissingJavadocMethod]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:39:27: Parameter operatingSystem should be final. [FinalParameters]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:39:43: 'operatingSystem' hides a field. [HiddenField]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:43: Line is longer than 80 characters (found 87). [LineLength]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:43:5: Class 'JdkPlatform' looks like designed for extension (can be subclassed), but the method 'runsOn' does not have javadoc that explains how to do that safely. If class is not designed for extension consider making the class 'JdkPlatform' final or making the method 'runsOn' static/final/abstract/empty, or adding allowed annotation for the method. [DesignForExtension]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:43:5: Missing a Javadoc comment. [MissingJavadocMethod]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:43:27: Parameter operatingSystem should be final. [FinalParameters]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:43:43: 'operatingSystem' hides a field. [HiddenField]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:43:60: Parameter architecture should be final. [FinalParameters]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:43:73: 'architecture' hides a field. [HiddenField]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:47: Line is longer than 80 characters (found 91). [LineLength]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:47:5: Class 'JdkPlatform' looks like designed for extension (can be subclassed), but the method 'runsOnAnyOperatingSystem' does not have javadoc that explains how to do that safely. If class is not designed for extension consider making the class 'JdkPlatform' final or making the method 'runsOnAnyOperatingSystem' static/final/abstract/empty, or adding allowed annotation for the method. [DesignForExtension]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:47:5: Missing a Javadoc comment. [MissingJavadocMethod]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:47:45: Parameter operatingSystems should be final. [FinalParameters]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:51:5: Class 'JdkPlatform' looks like designed for extension (can be subclassed), but the method 'toString' does not have javadoc that explains how to do that safely. If class is not designed for extension consider making the class 'JdkPlatform' final or making the method 'toString' static/final/abstract/empty, or adding allowed annotation for the method. [DesignForExtension]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:121:37: Parameter str should be final. [FinalParameters]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:129: Line is longer than 80 characters (found 87). [LineLength]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:129:9: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:129:14: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:129:23: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:129:30: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:129:39: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:129:46: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:129:55: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:129:64: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:129:73: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:129:80: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:129:85: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:133:9: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:133:14: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:133:19: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:133:26: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:133:33: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:133:42: Missing a Javadoc comment. [JavadocVariable]
```

**Review by M-Davies — CHANGES_REQUESTED** [review]
Linter issues (I realise they are not related to your changes but it would be good to get them fixed regardless 🙂)
```
Starting audit...
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:1: File does not end with a newline. [NewlineAtEndOfFile]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:1: Missing package-info.java file. [JavadocPackage]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:22:5: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:24:5: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:26:5: Missing a Javadoc comment. [MissingJavadocMethod]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:31:5: Class 'JdkPlatform' looks like designed for extension (can be subclassed), but the method 'runsOn' does not have javadoc that explains how to do that safely. If class is not designed for extension consider making the class 'JdkPlatform' final or making the method 'runsOn' static/final/abstract/empty, or adding allowed annotation for the method. [DesignForExtension]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:31:5: Missing a Javadoc comment. [MissingJavadocMethod]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:31:27: Parameter architecture should be final. [FinalParameters]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:31:40: 'architecture' hides a field. [HiddenField]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:35: Line is longer than 80 characters (found 82). [LineLength]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:35:5: Class 'JdkPlatform' looks like designed for extension (can be subclassed), but the method 'runsOnAnyArchitecture' does not have javadoc that explains how to do that safely. If class is not designed for extension consider making the class 'JdkPlatform' final or making the method 'runsOnAnyArchitecture' static/final/abstract/empty, or adding allowed annotation for the method. [DesignForExtension]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:35:5: Missing a Javadoc comment. [MissingJavadocMethod]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:35:42: Parameter architectures should be final. [FinalParameters]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:39:5: Class 'JdkPlatform' looks like designed for extension (can be subclassed), but the method 'runsOn' does not have javadoc that explains how to do that safely. If class is not designed for extension consider making the class 'JdkPlatform' final or making the method 'runsOn' static/final/abstract/empty, or adding allowed annotation for the method. [DesignForExtension]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:39:5: Missing a Javadoc comment. [MissingJavadocMethod]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:39:27: Parameter operatingSystem should be final. [FinalParameters]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:39:43: 'operatingSystem' hides a field. [HiddenField]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:43: Line is longer than 80 characters (found 87). [LineLength]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:43:5: Class 'JdkPlatform' looks like designed for extension (can be subclassed), but the method 'runsOn' does not have javadoc that explains how to do that safely. If class is not designed for extension consider making the class 'JdkPlatform' final or making the method 'runsOn' static/final/abstract/empty, or adding allowed annotation for the method. [DesignForExtension]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:43:5: Missing a Javadoc comment. [MissingJavadocMethod]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:43:27: Parameter operatingSystem should be final. [FinalParameters]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:43:43: 'operatingSystem' hides a field. [HiddenField]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:43:60: Parameter architecture should be final. [FinalParameters]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:43:73: 'architecture' hides a field. [HiddenField]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:47: Line is longer than 80 characters (found 91). [LineLength]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:47:5: Class 'JdkPlatform' looks like designed for extension (can be subclassed), but the method 'runsOnAnyOperatingSystem' does not have javadoc that explains how to do that safely. If class is not designed for extension consider making the class 'JdkPlatform' final or making the method 'runsOnAnyOperatingSystem' static/final/abstract/empty, or adding allowed annotation for the method. [DesignForExtension]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:47:5: Missing a Javadoc comment. [MissingJavadocMethod]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:47:45: Parameter operatingSystems should be final. [FinalParameters]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:51:5: Class 'JdkPlatform' looks like designed for extension (can be subclassed), but the method 'toString' does not have javadoc that explains how to do that safely. If class is not designed for extension consider making the class 'JdkPlatform' final or making the method 'toString' static/final/abstract/empty, or adding allowed annotation for the method. [DesignForExtension]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:121:37: Parameter str should be final. [FinalParameters]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:129: Line is longer than 80 characters (found 87). [LineLength]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:129:9: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:129:14: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:129:23: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:129:30: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:129:39: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:129:46: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:129:55: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:129:64: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:129:73: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:129:80: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:129:85: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:133:9: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:133:14: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:133:19: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:133:26: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:133:33: Missing a Javadoc comment. [JavadocVariable]
Error:  /github/workspace/test/functional/buildAndPackage/src/net/adoptopenjdk/test/JdkPlatform.java:133:42: Missing a Javadoc comment. [JavadocVariable]
```

**Comment by karianna** [comment]
I think if you rebase you might get the fixed lint changes

**Comment by sophia-guo** [comment]
Linter failures should be fixed in #2570

**Review by M-Davies — APPROVED** [review]

**Pull request merged**
