### PR TITLE
Use Freetype 2.10.2 across all pipelines

### PR DESCRIPTION
**Pull request by M-Davies**
* Upgrade our freetype version from 2.5.3/2.9.1 to 2.10.2

Closes: #1059 
Signed-off-by: Morgan Davies <morgan.davies@ibm.com>

### CODE REVIEW

**Comment by M-Davies** [comment]
@sxa FYI

**Comment by M-Davies** [comment]
Opened an inf issue requesting to run a couple of tests with newer freetype version

**Comment by Willsparker** [comment]
Just wondering, in what situation do we use Freetype `v2.9.1` ? I can only see your PR removing the `2.5.3` versions :-)

**Comment by M-Davies** [comment]
@Willsparker Since we don't specify it in the scripts, the builds pick up whichever freetype is on the machines https://github.com/AdoptOpenJDK/openjdk-build/issues/1059#issuecomment-632059663

**Comment by Willsparker** [comment]
It does..? 
[This run](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-hotspot/593/consoleFull ) ( JDK11/HS ) still downloaded and built Freetype- it was `2.9.1` though, to be fair, I just can't find where in the code it decided it to be `2.9.1` as opposed to [this run](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-openj9/601/consoleFull) ( JDK11/J9 ) which opted for `2.5.3` instead...
I know this has been discussed before, but if a build is detecting a version of freetype on the machine, why get the tar and build it again?

**Comment by sxa** [comment]
> And perhaps just a comment here that for 11+ we pick up what's already on the hosts.

@karianna Given that the [new JDK11 build failures](https://github.com/AdoptOpenJDK/openjdk-build/issues/1780) last night were due to freetype downloads, I don't believe that's the case (either that or we're still downloading unnecessarily ...)

The code that downloads it is at https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/prepareWorkspace.sh#L294

https://github.com/AdoptOpenJDK/openjdk-build/issues/1488 has not been implemented which would stop doing so.

**Comment by sxa** [comment]
Freetype is set to 2.9.1 as a default in the main build script configuration: https://github.com/AdoptOpenJDK/openjdk-installer/pull/212

However it is overridden in various cases in windows.sh: https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/platform-specific-configurations/windows.sh

**Comment by Willsparker** [comment]
@sxa I assume you meant here? : https://github.com/AdoptOpenJDK/openjdk-build/blob/adceff3deed77d862f90abb48115f49390cc8366/sbin/common/config_init.sh#L345
:-)

**Comment by M-Davies** [comment]
Thanks for all the work on https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1337. Regarding Stewart's comment on https://github.com/AdoptOpenJDK/openjdk-build/issues/466#issuecomment-634727945, getting all builds onto Freetype 2.10.2 is not really feasible right now due to VS2017 not being supported on JDK8 builds. 

We could, however, bump the following builds onto Freetype 2.10.2 since they do use TOOLCHAIN=2017:
- [x86_32-Windows-JDK11-OpenJ9](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/platform-specific-configurations/windows.sh#L86)(We don't build this platform in nightlies or releases) 
- [x86_32-Windows-JDK11-Hotspot(https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/platform-specific-configurations/windows.sh#L108)
- [x64-Windows-JDK11-OpenJ9](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/platform-specific-configurations/windows.sh#L139)
- [x64-Windows-JDK11-Hotspot](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/platform-specific-configurations/windows.sh#L172)

Thoughts?

**Comment by M-Davies** [comment]
Awaiting the result of https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1590664035346400. 

If we can't build JDK11-x86_32-Windows-Hotspot with Toolchain=2017, then this PR will need updating

**Comment by sxa** [comment]
Can you switch this into draft for now to ensure that it isn't merged in the immediate future :-)

**Comment by karianna** [comment]
> Thanks for all the work on [AdoptOpenJDK/openjdk-infrastructure#1337](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1337). Regarding Stewart's comment on [#466 (comment)](https://github.com/AdoptOpenJDK/openjdk-build/issues/466#issuecomment-634727945), getting all builds onto Freetype 2.10.2 is not really feasible right now due to VS2017 not being supported on JDK8 builds.
> 
> We could, however, bump the following builds onto Freetype 2.10.2 since they do use TOOLCHAIN=2017:
> 
> * [x86_32-Windows-JDK11-OpenJ9](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/platform-specific-configurations/windows.sh#L86)(We don't build this in nightlies or releases)
> * [x86_32-Windows-JDK11-Hotspot](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/platform-specific-configurations/windows.sh#L108)
> * [x64-Windows-JDK11-OpenJ9](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/platform-specific-configurations/windows.sh#L139)
> * [x64-Windows-JDK11-Hotspot](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/platform-specific-configurations/windows.sh#L172)
> 
> Thoughts?

I think we want to make it all or nothing so I'll try to pull in VS2017 expert to take a look

**Pull request closed without merging**
