### PR TITLE
Update groovy to 3.0.4 for all platforms

### PR DESCRIPTION
**Pull request by M-Davies**
Closes: #1880 
Signed-off-by: Morgan Davies <morgan.davies@ibm.com>

### CODE REVIEW

**Comment by M-Davies** [comment]
@sxa Is groovy downloaded automatically during the build or is it already present on the machines? I'm not sure if this PR will work or not if we specify a version that may not exist on the machines yet

**Comment by M-Davies** [comment]
Testing at https://ci.adoptopenjdk.net/view/work%20in%20progress/job/jdk15-mac-x64-openj9/1/console shows that we are missing some prereqs for groovy `3.0.4`. I'll update this PR

**Comment by sxa** [comment]
@karianna Did you intentionally move this to done based on a decision not to do the upgrade just now? If so we should explicitly state that :-)

**Comment by karianna** [comment]
Nope that was an accident

**Comment by M-Davies** [comment]
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/jdk15-mac-x64-openj9/4/consoleFull is passing on my branch. This can be merged tomorrow morning

**Comment by M-Davies** [comment]
I'm going to merge this and execute some test pipelines. We can always back it out if it doesn't work

**Comment by M-Davies** [comment]
JDK8 & 11 hotspot & riscv builds kicked off
- https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1120/console
- https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1018/console

**Pull request merged**
