### PR TITLE
Update JDK8/J9/Win to use VS2013 instead of VS2010

### PR DESCRIPTION
**Pull request by sxa**
Requested via https://github.com/AdoptOpenJDK/openjdk-build/issues/466#issuecomment-717285975

Signed-off-by: Stewart X Addison <sxa@redhat.com>

### CODE REVIEW

**Comment by sxa** [comment]
Validating at https://ci.adoptopenjdk.net/view/Tooling/job/VagrantPlaybookCheck/918/OS=Win2012,label=vagrant/

**Comment by sxa** [comment]
NOTE: Merging of this needs to be co-ordinated with OpenJ9 since it has to be synced with the merging of https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/449 and https://github.com/eclipse/openj9/pull/10892

**Review by karianna — APPROVED** [review]
LGTM

**Comment by sxa** [comment]
Note to reviewers: Failure on the checks is a macos compiler related error, so unrelated to this PR

**Review by M-Davies — APPROVED** [review]

**Comment by sxa** [comment]
Both upstream changes now merged, so merging this one.

**Pull request merged**
