### PR TITLE
Add Smoke tests for build & packaging

### PR DESCRIPTION
**Pull request by smlambert**
Tests from @aahlenst and @adamfarley moved from openjdk-tests repo PRs
Test job: https://ci.adoptopenjdk.net/view/work-in-progress/job/SmokeTestsForBuildandPackaging/

### CODE REVIEW

**Comment by smlambert** [comment]
Still to do:
- determine if any tests from FeatureTests.java are applicable to openj9 impl, assuming no, update test targets in playlist accordingly
- all functional tests can/should share utility methods for checking version, etc.  
- if we want VendorPropertiesTest for each vendor built at the project, use parameterization
- both impls are failing javaVendorVersion test, is it considered non-blocking?  related: https://github.com/AdoptOpenJDK/openjdk-build/issues/1387

**Comment by M-Davies** [comment]
Would these tests be used alongside our [existing suite?](https://github.com/AdoptOpenJDK/openjdk-build/tree/master/pipelines/src/test/groovy)

**Comment by smlambert** [comment]
The intent of these tests is to check that no one has made breaking changes (to what gets packaged for release).  This smoke set will grow to have several more checks, and could also include installer testing.  

They could get used alongside (or triggered at the same time) depending on when the existing set runs.  How/where is the existing suite triggered?  Part of PR testing? part of a pipeline run?  or both?  (yes, I can look to answer this myself ;) )

**Comment by M-Davies** [comment]
They're executed as part of the Compile pr tester on all build PR's (see https://github.com/AdoptOpenJDK/openjdk-build/tree/master/pipelines/build/prTester#Compile). You can also execute it locally:
```
cd pipelines
 ./gradlew --info test
```

**Comment by smlambert** [comment]
These smoke tests are meant to verify the build artifact that gets created (actually call java executable after its unpacked onto a machine), so they are not suitable to add to the Compile PR tester workflow.

I will look at the various points in our pipeline where they would be better applied, and note that they can even still exist as a standalone job rather than a step or a stage in the build pipeline.

(refering to the diagram at https://github.com/AdoptOpenJDK/TSC/issues/158#issuecomment-653664841 they could be the first subtest run after sign step and before any other tests run, and definitely before publish).

**Comment by karianna** [comment]
@smlambert  - Did you want to continue with this PR or are you happy to park it given our [refactoring efforts](https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1612353108094700)?

**Comment by aahlenst** [comment]
@karianna Getting this PR in should be **the single top-priority of this project**.

**Comment by karianna** [comment]
> @karianna Getting this PR in should be **the single top-priority of this project**.

In that case @smlambert - if you're happy with it can you take it out of draft and we can review and try to land.

**Comment by smlambert** [comment]
re: https://github.com/AdoptOpenJDK/openjdk-build/pull/2397#issuecomment-764205196
There are a couple of other things that should happen, but some can come in as subsequent PRs

https://github.com/AdoptOpenJDK/TKG/pull/142 has landed, I can update the SmokeTestsForBuildAndPackaging test job to not use my TKG branch now.

The [SmokeTestsForBuildAndPackaging](https://ci.adoptopenjdk.net/view/work-in-progress/job/SmokeTestsForBuildandPackaging/) job is running as a standalone, and should also get tied into the overall build pipeline (so that it can block further testing and publishing of build artifacts).

**Review by karianna — APPROVED** [review]
LGTM - I have a preference for one assert per test but it's not as hill I'm going to die on :-)

**Review by M-Davies — COMMENTED** [review]
Does any documentation in this repo need updating to inform/educate users of these changes?

**Review by sxa — APPROVED** [review]
On the basis that this is just the test cases being added which are called without requiring changes to the main build pipelines, I see no reason not to merge this

**Comment by smlambert** [comment]
Yes, still to do:
- add Andreas and Adam as co-authors

There will be PRs to follow this one:

- Trigger the smoke test job from the openjdk_build_pipeline.groovy with something like:
```
  /* 
    Run tests from the build repository that verify certain features are present and enabled,
    and system properties are correct.  These tests block further testing and publishing of 
    build artifacts.
    */
    def runBuildSmokeTests() {
        def jobName = "SmokeTestsForBuildandPackaging"
...
```

- Figure out where to put documentation (guidance for other build and packaging tests to follow, for example, guidance to someone adding new tests to verify contents of RELEASE file - related: https://github.com/AdoptOpenJDK/openjdk-build/pull/2413)
- testZGCAvailable is not failing when in error (see [example](https://ci.adoptopenjdk.net/view/work-in-progress/job/SmokeTestsForBuildandPackaging/15/tapResults/)) - I will see if I can figure that out today and either push to this PR, or follow with a separate one

**Comment by smlambert** [comment]
@M-Davies - per your question regarding doc, I will plan to add doc in the follow-up PR where this gets tied into the build pipeline itself (so the doc can describe that these tests will block other testing and publishing of artifacts).  

Currently anyone can trigger the [SmokeTestsForBuildandPackaging](https://ci.adoptopenjdk.net/view/work-in-progress/job/SmokeTestsForBuildandPackaging/) job, against any build produced at the project (just as you would any Grinder). 

Given there are 2 approvals on this, I will merge it and begin on the subsequent PR so that we automatically rather than manually launch the test job.

**Pull request merged**
