### PR TITLE
pipelines: Use variables to remove Windows workspaces

### PR DESCRIPTION
**Pull request by Willsparker**
Ref: #2205 , #1956 , #2204 , #2400 

The plan is to use a variable to remove the problematic Windows workspaces, as we have an awful lot of hard coded implementations now. PRs in draft until I can figure out what variables can actually be used!

ping @M-Davies , @Haroon-Khel , @sxa 

Signed-off-by: Will Parker <wills.parker@outlook.com>

### CODE REVIEW

**Comment by Willsparker** [comment]
run tests

**Comment by Willsparker** [comment]
Ah hang on- the `Compile Groovy` check has at least picked up that `${WORKSPACE}` is undefined. Removing now

**Comment by sxa** [comment]
Can you use the variable that the value of CYGWIN_WORKSPACE gets assigned to when it's defined?

**Comment by Willsparker** [comment]
I'll give it a go :-) the Groovy check will fail if the variable is undefined, so it's worth a go! :+1:

**Comment by Willsparker** [comment]
Okay, setting `${workspace}` didn't work. I'll try `${env.CYGWIN_WORKSPACE}`.

**Comment by M-Davies** [comment]
run tests

> Edit: Hmm, it appears I can't do that. @M-Davies would you mind? Also, is there a list of people who have access anywhere? I looked at the [README.md](https://github.com/AdoptOpenJDK/openjdk-build/pull/2400#issuecomment-766860979) you linked @Haroon-Khel , which alludes to it, but doesn't say where it is :-)

https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/prTester/README.md#add-to-whitelist. The last bullet links you to the https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/openjdk-build-pr-tester/ job: 🙂  
> Should you want the up to date admin or white list, check the configuration of the openjdk-build-pr-tester job. If you don't have the permissions to view the configuration, then try out the add to whitelist and run tests commands on a test PR to see if they work.

You might want to try env.CYGWIN_WORKSPACE and CYGWIN_WORKSPACE again on the pr tester itself. The Compile Groovy step only checks if the variables/functions exist in https://github.com/AdoptOpenJDK/openjdk-build/tree/master/pipelines/src/main/groovy and so are unrelated to what Jenkins variables we have on the server

**Comment by M-Davies** [comment]
add to whitelist

**Comment by M-Davies** [comment]
run tests

**Comment by Willsparker** [comment]
So, judging the PR-Build Tester, specifically (https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk11u/job/jdk11u-windows-x64-hotspot/481/consoleFull) , it seems to have _passed_, however I can't find any output in the log indicating that it did what it was meant to :sweat_smile:

**Comment by sxa** [comment]
FYI This may be rendered irrelevant by https://github.com/AdoptOpenJDK/openjdk-build/pull/2416

**Comment by Willsparker** [comment]
In case the #2416 doesn't fix the issue, I'll mark this as ready to review, as I think this fixes the issue :-)

**Review by M-Davies — APPROVED** [review]

**Review by sxa — APPROVED** [review]
Approved in principle but hopefully shouldn't be needed (would also result in a merge conflict with https://github.com/AdoptOpenJDK/openjdk-build/pull/2416 but thanks for investigating and producting a solution

**Comment by Willsparker** [comment]
Yeah, the mention PR was merged, so I'll close this one :+1:

**Pull request closed without merging**
