### PR TITLE
add OpenJ9 to aarch64 PR testing

### PR DESCRIPTION
**Pull request by gdams**

### CODE REVIEW

**Comment by sxa** [comment]
This replaces https://github.com/AdoptOpenJDK/openjdk-build/pull/2010 which went a bit weird (closed itself) when I forced pushed to the branch to add debug statements (!)

**Comment by gdams** [comment]
looking much better! https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk8u/job/jdk8u-linux-aarch64-openj9/3/console

**Comment by karianna** [comment]
@gdams - merge conflict

**Comment by karianna** [comment]
@M-Davies are the PR tester pipeline failures expected here?

**Comment by M-Davies** [comment]
To confirm, we only want to add openj9 to the pr tester here yes? The title is a little misleading is all. The failures don't look pr related anyhow

**Pull request merged**
