### PR TITLE
Populate "SOURCE" tag for jdk8u builds

### PR DESCRIPTION
**Pull request by austin0**
Fixes: #1966

General thoughts are referenced in https://github.com/AdoptOpenJDK/openjdk-build/issues/1966#issuecomment-674939773.

Signed-off-by: Austin Bailey <Austin.Bailey@ibm.com>

### CODE REVIEW

**Comment by douph1** [comment]
run tests

**Comment by Willsparker** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by austin0** [comment]
Changes seems to be working as expected.
```
JAVA_VERSION="1.8.0_272"
OS_NAME="Linux"
OS_VERSION="2.6"
OS_ARCH="amd64"
SOURCE=" .:git:f94631b4e2"
```

5 failures in the pr-tester pipeline: 2 installer failures, 2 git checkout failures, 1 alpine linux failure.

**Review by gdams — APPROVED** [review]

**Comment by andrew-m-leonard** [comment]
@austin0 From a Hotspot perspective this seems reasonable. However for OpenJ9 binaries it will only provide the openjdk extensions SHA, and not the additional openj9 and omr SHAs. If you compare with a jdk11 openj9 "release" file:
```
SOURCE="OpenJDK:838028fc9d OpenJ9:05fa2d361 OMR:d4365f371"
```
So maybe adding some conditional logic for if VARIANT is OPENJ9, also add the openj9 and omr SHAs, however with the current logic in make/common/MakeBase.gmk that maybe a little tricky, as that only searches the standard jdk8 sub-repos.

**Review by andrew-m-leonard — COMMENTED** [review]
@austin0 From a Hotspot perspective this seems reasonable. However for OpenJ9 binaries it will only provide the openjdk extensions SHA, and not the additional openj9 and omr SHAs. If you compare with a jdk11 openj9 "release" file:
```
SOURCE="OpenJDK:838028fc9d OpenJ9:05fa2d361 OMR:d4365f371"
```
So maybe adding some conditional logic for if VARIANT is OPENJ9, also add the openj9 and omr SHAs, however with the current logic in make/common/MakeBase.gmk that maybe a little tricky, as that only searches the standard jdk8 sub-repos.

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
whitelist

**Comment by austin0** [comment]
This seems good to go now.

OpenJ9:
```
JAVA_VERSION="1.8.0_265"
OS_NAME="Linux"
OS_VERSION="2.6"
OS_ARCH="amd64"
SOURCE=" .:OpenJDK: 182efd27:OpenJ9: 88a0575f9:OMR: e9496b7fe:"
```

Hotspot:
```
JAVA_VERSION="1.8.0_272"
OS_NAME="Darwin"
OS_VERSION="11.2"
OS_ARCH="x86_64"
SOURCE=" .:OpenJDK: ebf0755d3d:"
```

@andrew-m-leonard can you review this again?

**Review by andrew-m-leonard — APPROVED** [review]

**Comment by andrew-m-leonard** [comment]
@austin0 Looks good

**Pull request merged**
