### PR TITLE
sign: force windows to use 2012 machines

### PR DESCRIPTION
**Pull request by gdams**
fixes: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1616

### CODE REVIEW

**Review by Willsparker — APPROVED** [review]
LGTM

**Review by karianna — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
@gdams Any reason why we don't have signing enabled on >2012 machines?

**Comment by karianna** [comment]
> @gdams Any reason why we don't have signing enabled on >2012 machines?

Ah I saw the other issue

**Comment by karianna** [comment]
Created https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1617

**Pull request merged**
