### PR TITLE
Add systemtap-sdt to Dockerfiles

### PR DESCRIPTION
**Pull request by sauliusvl**
Needed for `--enable-dtrace` as described in https://github.com/AdoptOpenJDK/openjdk-build/issues/1242

### CODE REVIEW

**Comment by sxa555** [comment]
@willsparker We'll need to add these to your new dockerfiles for JDK11 and above

**Comment by sauliusvl** [comment]
> @sauliusvl Can you add a comment as to why it's being added? (New requirement for these scripts)

in the PR description, or document it somewhere? the rationale is described in the issue: https://github.com/AdoptOpenJDK/openjdk-build/issues/1242

**Comment by karianna** [comment]
> > @sauliusvl Can you add a comment as to why it's being added? (New requirement for these scripts)
> 
> in the PR description, or document it somewhere? the rationale is described in the issue: #1242

In a comment next to the package you added - we're moving towards self-documenting infra config. :-)

**Comment by sauliusvl** [comment]
> In a comment next to the package you added - we're moving towards self-documenting infra config. :-)

I can't just simply add it next to the package [here](https://github.com/sauliusvl/openjdk-build/blob/add-systemtap/docker/jdk10/x86_64/ubuntu/Dockerfile#L47), since it's a bash multi-line command, unless I do some crazy bash hack?
```bash
  systemtap-sdt-dev `# for --enable-dtrace` \
```

**Comment by karianna** [comment]
> > In a comment next to the package you added - we're moving towards self-documenting infra config. :-)
> 
> I can't just simply add it next to the package [here](https://github.com/sauliusvl/openjdk-build/blob/add-systemtap/docker/jdk10/x86_64/ubuntu/Dockerfile#L47), since it's a bash multi-line command, unless I do some crazy bash hack?
> 
> ```shell
>   systemtap-sdt-dev `# for --enable-dtrace` \
> ```

A silly me! Nevermind, let's just get this in.

**Pull request merged**
