### PR TITLE
Add JENKINS_AUTH Param to Job Generators

### PR DESCRIPTION
**Pull request by M-Davies**
* Adds JENKINS_AUTH param to allow users to upload custom credentials to interface with the Jenkins api should anonymous read be disabled
* Also cleans up some spelling and markdown linting issues in the regen documentation

Closes: #2044 
Signed-off-by: Morgan Davies morgandavies2020@gmail.com

### CODE REVIEW

**Comment by M-Davies** [comment]
https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/alpha_pipeline_jobs_generator/40/ tests this without creds. https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/alpha_pipeline_jobs_generator/41/ tests this with creds. Both tests passed

**Comment by M-Davies** [comment]
@AdamBrousseau Could you review this please?

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
run tests

**Review by AdamBrousseau — COMMENTED** [review]
LFTM. I was hoping to test this but my vpn is down at the moment so I can't access my instance. Hopefully it's back in the morning and I will update.

**Review by karianna — APPROVED** [review]
LGTM

**Review by AdamBrousseau — APPROVED** [review]
Sorry for the delay @M-Davies . I was able to test this with the new JENKINS_AUTH param and it worked. Thanks for the PR.

**Comment by M-Davies** [comment]
run tests

**Review by gdams — APPROVED** [review]

**Comment by gdams** [comment]
@M-Davies conflicts

**Pull request merged**
