### PR TITLE
Fixing issue with demo files not getting removed from with tarbal

### PR DESCRIPTION
**Pull request by neomatrix369**
Adding some echoes to the build.sh and common-functions.sh script files. Also changing to the image folder to be able to remove the AWT/GUI components from the demo folder in the newly created JDK image.

PR fixes issue #167.

### CODE REVIEW

**Comment by neomatrix369** [comment]
Cheating and building via https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk8_x86-64_linux_mani_pr_172/1/, don't know if this is the way to do it (new process?)

**Comment by neomatrix369** [comment]
I have noticed lines like this:
`if [...` fails on my local machine
and 

`if [[...` fails on Jenkins

See `sbin/common-functions.sh: line 103`, to see the block of code I'm talking about, there are a couple such places.

Anyone has any idea whats happening here?
Bash version issue?

```
bash --version
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
From my local env.

**Comment by neomatrix369** [comment]
Artifact is smaller than the previous builds: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk8_x86-64_linux_mani_pr_172/lastSuccessfulBuild/artifact/

**Comment by neomatrix369** [comment]
Kicked off https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk9_x86-64_linux_mani_pr_172/1/console for OpenJDK9

**Comment by neomatrix369** [comment]
(OpenJDK9) Artifact is smaller than the previous builds: 
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk9_x86-64_linux_mani_pr_172/lastSuccessfulBuild/artifact/

**Comment by neomatrix369** [comment]
Docker builds are failing, as the Dockerfiles are missing changes via PR #164

**Comment by karianna** [comment]
@neomatrix369 is the single [ and double [[ still an issue for you?

**Comment by neomatrix369** [comment]
@karianna Yes, single [ and double [[ still an issue, I wonder if anyone else with Debian Linux has the same

**Comment by neomatrix369** [comment]
@karianna @gdams Can someone the bash script on their local env,  preferably Debian Linux, or even MacOSX to see if there are any issues with it, although the [ and [[ is a separate issue to our original `.tar.gz` size issue.

**Comment by karianna** [comment]
@neomatrix369 I'll probably have to pair with you on this after J1 or maybe on the Monday coming - I haven't actually run the latest build/ docket scripts in quite some time.

**Comment by neomatrix369** [comment]
If no one has any further objections with this PR, I'll go ahead and merge it.

**Comment by karianna** [comment]
@neomatrix369 Go for it

**Pull request merged**
