### PR TITLE
Add arm32 builds to JDK15

### PR DESCRIPTION
**Pull request by M-Davies**
* Also deletes the duplicate arm32 config in jdk14

Closes: #1900 
Signed-off-by: Morgan Davies <morgan.davies@ibm.com>

### CODE REVIEW

**Comment by M-Davies** [comment]
@Willsparker Can I get a review please? :)

**Comment by M-Davies** [comment]
Job regenerator 15 [has finished](https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/pipeline_jobs_generator_jdk15/20/) and pulled in the new change. [JDK15-arm](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk15/job/jdk15-linux-arm-hotspot/) is ready to use @Willsparker

**Comment by Willsparker** [comment]
Thanks!

**Comment by karianna** [comment]
@M-Davies why was it removed from 14?  We'd still be building a 14.0.2 presumedly....

**Comment by karianna** [comment]
Oh never mind there was a duplicate

**Comment by sxa** [comment]
Running https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk15/job/jdk15-linux-arm-hotspot/ now

**Pull request merged**
