### PR TITLE
Load jenkins helper before building

### PR DESCRIPTION
**Pull request by M-Davies**
Signed-off-by: Morgan Davies <morgandavies2020@gmail.com>

### CODE REVIEW

**Comment by M-Davies** [comment]
Avoids problems seen in
- https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-aarch64-openj9/122/console
- https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-openj9/845/console
```
22:02:57  Failed test: java.lang.ClassNotFoundException: JobHelper
```

**Review by andrew-m-leonard — APPROVED** [review]
looks good

**Review by sxa — APPROVED** [review]
It seems this is affecting the production pipelines which are run in docker builds so I'm approving on the basis we need to get the releases out and this sounds like a plausible fix

**Review by karianna — APPROVED** [review]
LGTM

**Pull request merged**
