### PR TITLE
Updating Concurrent Pipeline Scripts

### PR DESCRIPTION
**Pull request by M-Davies**
Part 1 of Issue: #1701 
Signed-off-by: Morgan Davies <morgan.davies@ibm.com>

### CODE REVIEW

**Comment by M-Davies** [comment]
Ready for review

**Comment by sxa** [comment]
This shouldn't be in the main section as it's something that needs to be done asynchronously from a release and certainly not something that releasers should be worrying about during the quarterly cycle.

**Comment by sxa** [comment]
Also I would suggest that the line about updating the `JDK_HEAD` job isn't necessary in the section about removing an (old) JDK version as it's unlikely we'd be removing something that would affect the head (and people can hopefully use common sense if such an odd situation did occur.

**Comment by M-Davies** [comment]
Hmm. In that case, would that section be better suited in https://github.com/AdoptOpenJDK/openjdk-build/blob/master/RELEASING.md#openjdk-new-release in that case?

**Comment by M-Davies** [comment]
Or I could add the details on how to update the pipeline job generators to the [README](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/regeneration/README.md) in `/regeneration` and add a link in https://github.com/AdoptOpenJDK/openjdk-build/blob/master/RELEASING.md#openjdk-new-release to it? 

What is your opinion @sxa ?

**Comment by sxa** [comment]
I've been pondering this for a couple of hours (while doing other work I hasten to add!) and I'm still not quite sure ...

Note that there are other enhancements related to creating new releases that need to be added (probably not by you, but anyone who feels they have the information can do it!) under https://github.com/AdoptOpenJDK/openjdk-build/issues/1581

Given that the new sections is (fairly) long with quite a lot of steps, I'm inclined to put it in the `OpenJDK "New" Release` section, but move that section to the end of the document - purely because I want the important information for people doing a quarterly release to be at the top, and that's a separate thing dont every six months asynchronous to the release ... That also means there's an argument for having it as a separate document but I'd prefer to keep it in there just now.

So ... Let's move that section to the bottom of the document, add your bits into it (ideally change the bullet points to numbered steps for consistency and so that people can talk about things like "step 5" when discussing it online) By all means add a "For more information on the pipeline generation scripts see <link to your other doc that you've just added>" into that section too.

The info itself looks great though, so thanks for writing it :-D

**Comment by M-Davies** [comment]
Follow up PR to address the above https://github.com/AdoptOpenJDK/openjdk-build/pull/1709

**Pull request merged**
