### PR TITLE
start using dynamic docker setup for certain ppc64le builds

### PR DESCRIPTION
**Pull request by gdams**
related to https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1524

### CODE REVIEW

**Review by aahlenst — COMMENTED** [review]
Does that mean we build with CentOS 7 in the future? What happens with our promise to support CentOS 6's glibc? Or have we already included the necessary packages in our containers?

**Comment by aahlenst** [comment]
@gdams Can you elaborate on what "certain" means?

**Review by karianna — APPROVED** [review]
lgtm

**Comment by gdams** [comment]
@aahlenst we only support centos6 on x64. Not ppc64le.

Certain means jdk15 and jdk16 for now to ensure that things are stable before switching to an LTS build

**Comment by karianna** [comment]
@gdams build failures.

**Review by aahlenst — APPROVED** [review]

**Pull request merged**
