### PR TITLE
[WIP] Change default arm32 (armv7l) from zero to client VM and aarch32 hg repo

### PR DESCRIPTION
**Pull request by sxa555**
If anyone knows why we are buliding with a zero vm on arm32 and should leave it that way, speak now or forever hold your peace :-) 

But should this be client or server? What's the likely use cased for people on arm32?
The default java on the arm32 system that I've just looked at is using a client build of openjdk by default (and for my personal use it'll mostly be stuff on a raspberry pi/beaglebone where client feels more appropriate) so that's what I've set this to, although we set server on most of the others so maybe we should be consistent.

Happy with either option though since it'll be better than the zero VM ...

Suggest that reviews hold off on merging for a few days to ensure
- People get a chance to comment
- I can verify that it builds properly with a proper JIT (Running tests now but it'll take the best part of a day to verify them all

### CODE REVIEW

**Comment by sxa555** [comment]
https://ci.adoptopenjdk.net/job/openjdk8_build_arm32_linux/38/ failed trying to pass `-march=i586` into the build for some reason, so some additional work may be required ...

**Comment by tellison** [comment]
I'll hold off until you have had a chance to investigate the `i586` problem

**Comment by sxa555** [comment]
FYI 9 completed ok - going to run a 10 build using my "new" 9 as the boot JDK and see what difference it makes

**Comment by karianna** [comment]
http://mail.openjdk.java.net/pipermail/aarch32-port-dev/2017-January.txt was an old thread which might help

**Comment by sxa555** [comment]
After an initial scan of that the response to the error seems to be "It looks like you are cross-compiling it," which I'm not (although I was starting to come to the conclusion that the build process has convinced itself that I was!)  Whatever the problem is, it only exists when you try to build a JITted VM and it doesn't occur on openjdk9 and above.

**Comment by jerboaa** [comment]
@sxa555 From which sources are you building? Fedora's 32 bit arm JIT package uses http://hg.openjdk.java.net/aarch64-port/jdk8u/ and configures with `--with-jvm-variants=client":
https://src.fedoraproject.org/rpms/java-1.8.0-openjdk-aarch32/blob/master/f/java-1.8.0-openjdk-aarch32.spec#_1669

That built fine a couple of weeks back:
https://koji.fedoraproject.org/koji/buildinfo?buildID=1086883

Anyway, @akashche is your guy for 32 bit arm JIT builds :)

**Comment by sxa555** [comment]
I'm pulling from the adoptopenjdk/openjdk-jdk8u repo which is a straight mirror of the hg repo at the moment AFAIK. The aarch64 one seems ok - have only seen the issue with 32 so hopefully @akashche can offer some advice :-)

**Comment by akashche** [comment]
@sxa555 hi, this [repo](https://github.com/ojdkbuild/contrib_jdk8u-aarch32-ci) with cross-compile Travis setup for jdk8u-aarch32 may help. Build script there can be used (with minimal changes) locally without Travis. Please ping me (here or on email) if you have more questions about it.

**Comment by sxa555** [comment]
@akashche That looks like it's cross compiling though - I'm trying to build natively on arm32

**Comment by akashche** [comment]
@sxa555 native builds from [aarch32-port/jdk8u forest](http://hg.openjdk.java.net/aarch32-port/jdk8u/) should work with `--with-jvm-variants=client` argument.

**Comment by sxa555** [comment]
@akashche Thanks - prototyped at https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk8_build_aarch32_linux/6/console and seems to build ok although it's a shame not to be able to build it from the same codebase :-\

**Comment by sxa555** [comment]
This needs a few tweaks to the build scripts in order to pull from the aarch32 mercurial repository, so I'm going to leave this for now until we implement the new build scripts otherwise I'm going to be double fixing.

**Comment by karianna** [comment]
@sxa555 New build scripts are now in master, so hopefully can restart this?

**Comment by karianna** [comment]
@sxa555 Beep boop :-)

**Comment by sxa555** [comment]
@karianna I think our JDK11 builds are using a server VM now. Is there any outstanding issue here that you know of or shall I just cancel this PR?

**Pull request closed without merging**
