### PR TITLE
WIP: Set test build parameters in repo

### PR DESCRIPTION
**Pull request by sophia-guo**
For openjdk8/openjdk8-openj9 target is openjdk
For openjdk9 and up target is sanity.openjdk
Arm and windows limit target to jdk_math( due to running time)

Signed-off-by: Sophia Guo <sophiag@ca.ibm.com>

### CODE REVIEW

**Comment by karianna** [comment]
@sophia-guo can you rebase with master and push again - that should clear the travis issue.  Is this still also a WIP?

**Comment by sophia-guo** [comment]
@karianna there will be more changes in this PR. Leave it as WIP. Thanks.

**Comment by karianna** [comment]
Hmm, not sure why travis is trying to install shellcheck that way with the new `travis.yml`

**Comment by sophia-guo** [comment]
Close for now. Will work on it later.

**Pull request closed without merging**
