### PR TITLE
Revert "Update branch of openjdk8-openj9 to openj9-0.8"

### PR DESCRIPTION
**Pull request by sxa555**
This reverts commit d0e331732423bcb8d9086975b7191dd4d04badb6.

### CODE REVIEW

**Comment by karianna** [comment]
Why does this need reverting?

**Comment by sxa555** [comment]
@karianna The switch was made specifically to build the release off the separate branch that the repository under ibmruntimes is using. This switches it back to the development branch now that the release has been done.

**Comment by karianna** [comment]
Hmmm, are we going to have to repeat this each time ibmruntimes puts out a version?

**Comment by sxa555** [comment]
@karianna 

Short answer: Not necessarily ... 

Long answer: I was initially envisaging using the tag parameter for this (as from a github perspective checking out a tag and branch are the same) but while that worked it left us with the branch name (openj9-0.8.0) as the top level directory in the resultant tgz file, so as a "quick fix" I modified the script which also has the advantage of not risking forgetting to set the parameter to the branch. Going forward, Adding a separate "branch" parameter which won't cause an override in the top level directory name in the tgz is almost certainly the better option and would remove any need to make changes such as these.

**Comment by gdams** [comment]
+1 on adding a branch parameter

**Pull request merged**
