### PR TITLE
Pass patch number into installer job

### PR DESCRIPTION
**Pull request by adamfarley**
Patch numbers have been added into the upstream build jobs for Windows,
but are not passed downstream, where it appears to prevent us from
finding the build in the installer job.

Signed-off-by: Adam Farley <adfarley@redhat.com>

### CODE REVIEW

**Comment by adamfarley** [comment]
Ok, I think here's the fix for the Windows installer issue seen [here](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/9306/console):

Step 1: Add "PRODUCT_BUILD_NUMBER" as a parameter for the create_windows_installer job.
Step 2: Replace all references to "PRODUCT_PATCH_VERSION" in the create_windows_installer job with "PRODUCT_BUILD_NUMBER"
Step 3: Change the create_windows_installer job so that we search for major.minor.maintenance.patch+build as the "fourth" step here:
J:\jenkins\workspace\build-scripts\release\create_installer_windows\wix>IF NOT "" == "true" 
Generate OpenJDK setup "hotspot" for "x64" platform "jdk"
****************************************************
First .\SourceDir\OpenJDK11\hotspot\x64\jdk-11.0.9 not exists
Second .\SourceDir\OpenJDK11\hotspot\x64\jdk-11+1 not exists
Third .\SourceDir\OpenJDK11\hotspot\x64\jdk-11.0.9+1 not exists
Step 4: Merge this PR

Does that sound right?

**Comment by sxa** [comment]
Instead of renaming the existing ones we could just add `PRODUCT_FIX_NUMBER` to handle the "new" (usually empty!) number

**Comment by adamfarley** [comment]
This is true, though since Andrew's new variable inside Version Info is called "patch" (e.g. major.minor.security.patch+build), I was trying for consistency with the variable names.

I'm happy to set "consistency" aside for now if it poses a problem, or makes things significantly more difficult.

**Comment by adamfarley** [comment]
This PR is paired with https://github.com/AdoptOpenJDK/openjdk-installer/pull/258

Both should be merged at the same time, ideally when no Windows jobs are running.

**Comment by karianna** [comment]
@adamfarley should this still be WIP?

**Review by karianna — APPROVED** [review]
LGTM

**Review by douph1 — APPROVED** [review]
It's good to see this kind if error fixed : PATCH != buildNumber

Where does the buildNumber come from ? Jenkins job build number ?

**Comment by andrew-m-leonard** [comment]
@douph1 Can we simply make this code: https://github.com/AdoptOpenJDK/openjdk-installer/blob/fe8c79d25551401db3cb06b3c7a72f013a56051c/wix/Build.OpenJDK_generic.cmd#L111
Query the folder: .\SourceDir\!PRODUCT_SKU!!PRODUCT_MAJOR_VERSION!\!PACKAGE_TYPE!\!FOLDER_PLATFORM!\jdk-*
to work out what the jdk-* path is?

**Comment by adamfarley** [comment]
> 
> 
> @douph1 Can we simply make this code: https://github.com/AdoptOpenJDK/openjdk-installer/blob/fe8c79d25551401db3cb06b3c7a72f013a56051c/wix/Build.OpenJDK_generic.cmd#L111
> Query the folder: .\SourceDir!PRODUCT_SKU!!PRODUCT_MAJOR_VERSION!!PACKAGE_TYPE!!FOLDER_PLATFORM!\jdk-*
> to work out what the jdk-* path is?

Good idea for a new PR, I think.

Right now I'm looking at the JDK8 issue.

P.S. https://github.com/AdoptOpenJDK/openjdk-build/pull/2219/files should go in before this change, so they merge properly.

**Comment by adamfarley** [comment]
JDK8 issue resolved.

**Pull request merged**
