### PR TITLE
Update hardcoded JDK next values

### LINKED ISSUE #1514: Hard-coded JDK next values should be updated
Hard-coded jdknext values 15 should be updated so that they point to JAVA_FEATURE_VERSION in 
https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/make-adopt-build-farm.sh

Instances:
https://github.com/AdoptOpenJDK/openjdk-build/blob/cf9e7c1e092461b36f73503433cea8090f4da6e5/pipelines/build/common/build_base_file.groovy#L212
https://github.com/AdoptOpenJDK/openjdk-build/blob/177a4588c98f0770b132df2d7e26aa6946a7143b/pipelines/build/common/openjdk_build_pipeline.groovy#L65

### PR DESCRIPTION
**Pull request by ShishirH**
https://github.com/AdoptOpenJDK/openjdk-build/issues/1514

Closes #1514 

Signed-off-by: Shishir Halaharvi <shishir.neo95@gmail.com>

### CODE REVIEW

**Comment by ShishirH** [comment]
@adam-thorpe Please let me know if there is anything left to be done.

**Comment by adam-thorpe** [comment]
Think it was just those two values, thanks @ShishirH

**Comment by ShishirH** [comment]
@jerboaa Made suggested changes

**Comment by ShishirH** [comment]
@jerboaa Updated the message.

**Comment by jerboaa** [comment]
Looks good.

**Comment by johnoliver** [comment]
I am not sure where we would set `JAVA_FEATURE_VERSION` so that these scripts would pick it up

**Comment by johnoliver** [comment]
I realise my last comment was a bit cryptic, for further info, the scripts you are changing execute on the Jenkins maser server, I am not sure they even are able to access the environment variables due to the jenkins sandbox, but also I am not sure we have a good way of setting that environment variable in the context of the jenkins scripts.

**Comment by jerboaa** [comment]
@karianna @johnoliver:

early on in build-farm/make-adopt-build-farm.sh:

https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/make-adopt-build-farm.sh#L26
https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/make-adopt-build-farm.sh#L32

Would jenkins master not execute this?

**Comment by adam-thorpe** [comment]
Looking at @sxa555 's lovely diagram in https://github.com/AdoptOpenJDK/openjdk-build/issues/957, `make-adopt-build-farm.sh` is called after `build_base_file.groovy` and `openjdk_build_pipeline.groovy` so the value is set later on (i.e. once the job has been initialised by jenkins)

**Comment by johnoliver** [comment]
Yes that is correct, the groovy files are run by jenkins to setup and configure the jobs, make-adopt-build-farm.sh comes after to do the actual build on the node. So `JAVA_FEATURE_VERSION` should not be set from inside the groovy code

**Comment by ShishirH** [comment]
@johnoliver @adam-thorpe If I understand correctly, due to the scripts running before the groovy code, the hardcoding shouldn't be removed, and both this PR and issue should be closed without merging, right?

**Comment by johnoliver** [comment]
@ShishirH its the other way around, since the groovy runs before the scripts so the variable is not set for the groovy to pick up. Removing the hardcoding is good so I would like to find a way around it. One thing to note is that you can set global environment variables inside Jenkins, so this PR would work if you did that. Its possible we could use Jenkins global environment variables as a central place to encode what the most recent version is. 

It is an open question as to where we want to centralise this most recent version number information rather than have it scattered around lots of scripts. The api may be the correct place for it, or possibly putting it in Jenkins via a statically hosted file or environment variable. @karianna or @sxa555 may have an opinion on which would be better.

**Comment by karianna** [comment]
The API is intriguing as it decouples us from Jenkins (we're too tightly coupled as it is).  Are you thinking of something like https://api.adoptopenjdk.net/latest_jdk_version which would return say `15`?

**Comment by johnoliver** [comment]
@karianna yeah, something we can bump in a single place to pretty much say what version head is, then other scripts like docker stuff can read from there too.

**Comment by karianna** [comment]
@johnoliver Works for me, let's do it.

**Comment by M-Davies** [comment]
Created https://github.com/AdoptOpenJDK/openjdk-api-v3/issues/212 to follow up on this

**Pull request merged**
