### PR TITLE
Enable OpenJ9 builds of JDK-Next (15)

### PR DESCRIPTION
**Pull request by M-Davies**
Closes: #1776 
Signed-off-by: Morgan Davies <morgan.davies@ibm.com>

### CODE REVIEW

**Comment by M-Davies** [comment]
Other requirements for this:
- Update the hard coded `targetConfigurations` variable in the [pipeline job](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk15-pipeline/)
- Create the downstream jobs manually (if the pipeline doesn't auto make them) https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk/

**Comment by karianna** [comment]
@M-Davies - you want me to land this or wait until l you've fixed the other issues?

**Comment by M-Davies** [comment]
May as well land this. It won't affect the pipelines yet anyway

**Comment by M-Davies** [comment]
Pipeline didn't automatcally make the jobs so I made them myself. Let's land this and see how they do :)

**Comment by M-Davies** [comment]
Job regenerators have been kicked off (manually, not sure if the GIT polling doesn't work or not anymore 🤔). They'll be done when Jenkins comes back up

**Comment by M-Davies** [comment]
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk15-pipeline/141/console looks good!

**Pull request merged**
