### PR TITLE
Add repo as a parameter to mercurial clone job. Fix #1074

### LINKED ISSUE #1074: JDK 12 build is failing
According to the [build farm of JDK12](https://ci.adoptopenjdk.net/view/git-hg/job/git-hg/job/git-hg-jdk12u/) this build has been failing since April 16. 

I'd like to help out, but I need some assistance getting started.

### PR DESCRIPTION
**Pull request by johnoliver**

### CODE REVIEW

**Comment by adamfarley** [comment]
@johnoliver - it looks like Martijn had quality concerns over this PR prior to rubber-stamping the merge.

@karianna - I've re-opened the related issue, as the fix isn't merged. Can this PR be linked to the issue please?

**Comment by johnoliver** [comment]
Unfortunately I cant see from that page what it is complaining about

**Comment by adamfarley** [comment]
Me neither tbh. I was hoping you knew something about codacy that I didn't.

Will put a note on Slack.

**Comment by adamfarley** [comment]
Closing on johno's recommendation.

**Pull request closed without merging**
