### PR TITLE
Run full build pipeline from PR

### PR DESCRIPTION
**Pull request by johnoliver**

### CODE REVIEW

**Comment by johnoliver** [comment]
run tests

**Comment by karianna** [comment]
@johnoliver Aborted?

**Comment by johnoliver** [comment]
rerun tests

**Comment by johnoliver** [comment]
rerun tests

**Comment by johnoliver** [comment]
rerun tests

**Comment by johnoliver** [comment]
This pr should be good

**Comment by karianna** [comment]
@johnoliver LGTM - Is it clear in the Jenkins view that a (currently Linux x86 only) build job was kicked off from a PR as opposed to a 'regular' run?

**Comment by johnoliver** [comment]
The live jobs and the PR test jobs are not the same jobs, they live in different folders

**Pull request merged**
