### PR TITLE
Docker JDK_PATH Variable

### PR DESCRIPTION
**Pull request by EnriqueL8**
Passing JDK_PATH env variable to docker

### CODE REVIEW

**Comment by karianna** [comment]
What's it used for?

**Comment by neomatrix369** [comment]
`ENV JDK_PATH=jdk` @gdams what is this trying to achieve in the context of the container both on the host machine and inside the container?

**Comment by karianna** [comment]
@EnriqueL8 Build is failing for this PR.  Maybe check with @gdams as well - perhaps this is no longer required?

**Comment by neomatrix369** [comment]
TravisCI has some how looped this build into its shellcheck failure, although @EnriqueL8 change has to do with docker changes only

**Comment by gdams** [comment]
Can this be closed? I think that @mstoodle already applied this fix

**Comment by karianna** [comment]
run tests

**Comment by tellison** [comment]
This PR is obsolete.  Please open a new request if required.

**Pull request closed without merging**
