### PR TITLE
build: Disable buildSharedLibs as it does not seem to be needed

### PR DESCRIPTION
**Pull request by sxa**
Controversial? Maybe, but we [disabled it for Solaris/SPARC](https://github.com/AdoptOpenJDK/openjdk-build/pull/2228) for performance reasons a while back and it did not appear to cause any obvious problems ([reinstated](https://github.com/AdoptOpenJDK/openjdk-build/pull/2399) once a particular issue with the build system was fixed) and [based on the Slack threads](https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1605110513432600) which I've tried to start on this topic no-one was able to tell me why it was strictly required, and since the gradle code here has been the cause of various build failures in the last year or so I'm proposing stripping it out to resolve https://github.com/AdoptOpenJDK/openjdk-build/issues/2139 unless someone can come up with a good reason to retain it (it may be used in the metadata processing but if so I suspect that can be replicated trivially without java and gradle. If it does cause any problems, we should ensure that the tests being put in place for https://github.com/AdoptOpenJDK/openjdk-tests/pull/2067 can pick it up :-)

Signed-off-by: Stewart X Addison <sxa@redhat.com>

### CODE REVIEW

**Comment by M-Davies** [comment]
run tests

**Review by M-Davies — APPROVED** [review]
Based off the high level of testing and feedback, I think this is a safe and good change

**Comment by sxa** [comment]
> Based off the high level of testing and feedback, I think this is a safe and good change

And if not we've got a good six weeks before the next release to find any problems 😁

**Review by aahlenst — APPROVED** [review]

**Comment by sxa** [comment]
NOTE to reviewers: Please leave this for me to merge at a suitable time

**Comment by sxa** [comment]
@andrew-m-leonard Hmmm unsure if it's coincidence but after this has gone in the first build I ran came back with an `OpenJ9` SHA of `unknown`
```
16:12:19  Eclipse OpenJ9 VM (build master-95ba1bfd8, JRE 1.8.0 Mac OS X amd64-64-Bit 20210201_665 (JIT enabled, AOT enabled)
16:12:19  OpenJ9   - unknown
16:12:19  OMR      - 7b4155a69
16:12:19  JCL      - a808307b based on jdk8u282-b08)
16:12:32  build.sh : 16:12:30 : Build complete ...
```

**Comment by sxa** [comment]
Worryingly https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-mac-x64-openj9/849/consoleFull had a segfault.

The other thing that has changed today is the [move to cmake across all current OpenJ9 versions](https://github.com/AdoptOpenJDK/openjdk-build/issues/2424)

**Comment by andrew-m-leonard** [comment]
> Worryingly https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-mac-x64-openj9/849/consoleFull had a segfault.
> 
> The other thing that has changed today is the [move to cmake across all current OpenJ9 versions](https://github.com/AdoptOpenJDK/openjdk-build/issues/2424)

The seg fault 11 has been seen before: https://github.com/eclipse/openj9/issues/11292

**Pull request merged**
