### PR TITLE
Verify branch exists when creating a new repo and chunk commit uploads

### PR DESCRIPTION
**Pull request by johnoliver**

### CODE REVIEW

**Comment by johnoliver** [comment]
run tests

**Comment by johnoliver** [comment]
run tests

**Comment by johnoliver** [comment]
run tests

**Comment by johnoliver** [comment]
run tests

**Comment by karianna** [comment]
@johnoliver Not sure if the Pull Request Builder failing is a problem...

**Comment by johnoliver** [comment]
rerun tests

**Comment by johnoliver** [comment]
rerun tests

**Comment by johnoliver** [comment]
run tests

**Comment by johnoliver** [comment]
run tests

**Comment by karianna** [comment]
@johnoliver https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/openjdk-build-test-pr/11/console failed?

**Comment by johnoliver** [comment]
rerun tests

**Comment by johnoliver** [comment]
rerun tests

**Pull request merged**
