### PR TITLE
show downstream job results

### PR DESCRIPTION
**Pull request by gdams**

### CODE REVIEW

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Review by karianna — APPROVED** [review]
LGTM

**Comment by karianna** [comment]
@gdams Did you mean to close this as opposed to merging?

**Pull request closed without merging**
