### PR TITLE
Switch JDK15/J9 back to centos7 build image

### PR DESCRIPTION
**Pull request by sxa**
Ref: https://github.com/AdoptOpenJDK/openjdk-build/pull/2154#issuecomment-712908452

Signed-off-by: Stewart X Addison <sxa@redhat.com>

### CODE REVIEW

**Comment by sxa** [comment]
run tests

**Review by gdams — APPROVED** [review]

**Review by karianna — APPROVED** [review]
LGTM

**Review by aahlenst — APPROVED** [review]
Thanks a lot, @sxa.

**Comment by karianna** [comment]
@sxa Do we land this before release?

**Comment by sxa** [comment]
> @sxa Do we land this before release?
I think we have to but I'm holding off until either
1. The checks complete (Looks like only aarch64 has failed so far for reasons that have nothing to do with this PR and have been corrected - I have another PR test run queued up)
2. The upstream code is released
At some point this evening I may land it regardless of whether both of those conditions have been met, but I wanted to give enough time for anyone who wanted to object to landing it before GA

**Comment by sxa** [comment]
Merging as this looks to be ok other than the known aarch64 issues and I don't want to risk missing this. The builds all look like they've used the correct images after this change (As a side effect this will also [fix JDK16/J9 immediately too](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1635), though not HotSpot until the next GA goes out or https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1639 gets merged)

**Comment by sxa** [comment]
Merging on the basis that we have four TSC approvals for this, and it has been requested for the GA. All builds from the PR tester look to have run in the correct environment

**Pull request merged**
