### PR TITLE
Update weekend release test pipelines so they do not lock Jenkins logs

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Add a new build pipeline param keepReleaseLogs which defaults to true, but weekend test builds set to false.

Signed-off-by: Andrew Leonard <anleonar@redhat.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
run tests

**Comment by andrew-m-leonard** [comment]
run tests

**Review by karianna — APPROVED** [review]
lgtm

**Review by M-Davies — APPROVED** [review]

**Pull request merged**
