### PR TITLE
OpenJ9/aarch64: --disable-warnings-as-errors

### PR DESCRIPTION
**Pull request by sxa555**
Required for https://github.com/AdoptOpenJDK/openjdk-build/issues/966

Signed-off-by: Stewart Addison <sxa@uk.ibm.com>

### CODE REVIEW

**Comment by karianna** [comment]
Won't merge until after April 16th release though

**Comment by tellison** [comment]
From the peanut gallery: seems like a sledgehammer approach to solve the one reported instance of a warning, thereby leaving us open to missing new warnings in the future that may be valuable.

As @knn-k [wrote in the cause](https://github.com/eclipse/openj9/issues/4486#issuecomment-483511330), it would be preferable for OpenJ9 to add a compiler pragma.

**Comment by knn-k** [comment]
I just opened https://github.com/eclipse/openj9/pull/5508 as an alternative solution for AArch64 build.

**Comment by sxa555** [comment]
@tellison Totally agree which is why I really didn't want to do this and delayed it a while. I only ever intended this to be a temporary fix until we got something better. As it happens https://github.com/eclipse/openj9/pull/5508 is now ready to go in, therefore I am going to cancel this PR.

**Pull request closed without merging**
