### PR TITLE
Update the logic for launching tests

### PR DESCRIPTION
**Pull request by llxia**
With new test jobs are generated (test job name change), we need to
update the way tests are launched

Issue: #1116

Signed-off-by: lanxia <lan_xia@ca.ibm.com>

### CODE REVIEW

**Comment by karianna** [comment]
@llxia Can you rebase, please?  I'll also review and then get @johnoliver to take a look

**Comment by smlambert** [comment]
@llxia is at a conference right now.  I want to make sure we have generated the right jobs https://github.com/AdoptOpenJDK/openjdk-tests/issues/1168 in order to support this, so would like to wait to merge this for now.  Waiting for a confirmation from Lan that we are good to go.

**Comment by llxia** [comment]
> @llxia Can you rebase, please? I'll also review and then get @johnoliver to take a look

Rebased.

**Comment by johnoliver** [comment]
is it ready for merging? I am fine with this as is and I have added my approve. But presumably all the new test names that it refers to need to be in place, are they all ready to go? 

Also as this pull request is currently a Draft we are not able to merge it, so if it is ready to go let us know and make it a non-draft.

**Comment by llxia** [comment]
I will test this PR using the pipeline build. If the test run passes, I will change it to `Ready for review`.

**Comment by johnoliver** [comment]
run tests

**Comment by llxia** [comment]
Please see the following testing builds: 

https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk11u/job/jdk11u-linux-x64-openj9/6/
https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk11u/job/jdk11u-linux-x64-hotspot/126/
https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk8u/job/jdk8u-mac-x64-hotspot/7/

Test jobs are triggered and executed correctly. Please note external test jobs cannot be auto-gened as they are the top-level test jobs and have special configuration. I will manually rename the top level external test job names to match with the new naming convention once the PR is merged.

This PR is ready to merge.

**Comment by smlambert** [comment]
Test runs look good, thanks @llxia !  Will merge now, as already 2 approvals

**Pull request merged**
