### PR TITLE
Updating the new hg for jdk 10 repo

### PR DESCRIPTION
**Pull request by neomatrix369**
After a number of tests it appears we are incorrectly clone repos starting JDK10, internal structure has changed hence change to script, these need testing before we merge them.

### CODE REVIEW

**Comment by neomatrix369** [comment]
@gdams I have renamed `openjdk-jdk10` to `openjdk-jdk10-backup` and created a new empty repo `openjdk-jdk10` with regards to testing this PR.

Currently running https://ci.adoptopenjdk.net/view/git-hg/job/git-hg-10/2696/console (setup script) as it kept failing on the old repo, so testing it with a fresh empty repo.

If this works, we can drop the backup repo,

**Comment by neomatrix369** [comment]
In response to https://github.com/AdoptOpenJDK/openjdk-build/pull/217#issuecomment-363276665, at the end of the execution, the push failed as I had not setup the rights on the repo:
```
...
Push
ERROR: Permission to AdoptOpenJDK/openjdk-jdk10.git denied to adoptopenjdk-github-bot.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

I have done it now and manually executed the same push command as in the script from inside the Jenkins box:

```
[jenkins@fedora-le-1 combined]$ git push github master --tags
Counting objects: 803697, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (140380/140380), done.
Writing objects: 100% (803697/803697), 1.77 GiB | 35.00 MiB/s, done.
Total 803697 (delta 616623), reused 803697 (delta 616623)
remote: Resolving deltas: 100% (616623/616623), done.
remote: Checking connectivity: 803697, done.
To git@github.com:AdoptOpenJDK/openjdk-jdk10.git
 * [new branch]      master -> master
 * [new tag]         jdk-10+0 -> jdk-10+0
 * [new tag]         jdk-10+1 -> jdk-10+1
 * [new tag]         jdk-10+10 -> jdk-10+10
 * [new tag]         jdk-10+11 -> jdk-10+11
 * [new tag]         jdk-10+12 -> jdk-10+12
<----------------------  snipped ----------------->
 * [new tag]         jdk9-b93 -> jdk9-b93
 * [new tag]         jdk9-b94 -> jdk9-b94
```
So the script was fine, we just needed a fresh repo for `openjdk10`.

**Comment by neomatrix369** [comment]
Ran the new update script (`update-without-modules.sh`), and it was successful, see https://ci.adoptopenjdk.net/view/git-hg/job/git-hg-10/2699/console.

**Comment by neomatrix369** [comment]
We will still need to apply the changes to `jdk-11` as a separate task. Check if jdk 8 and jdk 9 are being build correctly, this latter task is also connected to issue #211.

**Comment by neomatrix369** [comment]
Run `git-hg-diff` Jenkins job, see https://ci.adoptopenjdk.net/view/git-hg/job/git-diff-10/138/console, after creating a new script that does not call `get_source.sh`, as JDK10 onwards we don't have it, single repo - no more repo of repos concept.

**Comment by karianna** [comment]
@neomatrix369 I think your script renames aren't reflected in the calling scripts..

**Comment by neomatrix369** [comment]
@karianna that new script (`diff-without-getsource.sh`) is run directly via https://ci.adoptopenjdk.net/view/git-hg/job/git-diff-10/, isn't called from anywhere else, good spot, although the change is fine.

**Comment by neomatrix369** [comment]
The the script changes have been tested via the git-hg-... related Jenkins jobs and run fine for `jdk/jdk10`

**Pull request merged**
