### PR TITLE
Add sanity check on FILENAME

### PR DESCRIPTION
**Pull request by johnoliver**

### CODE REVIEW

**Comment by karianna** [comment]
Unrelarted build failures?

```
TestCompilation > openjdk_build_pipelineTest() STANDARD_ERROR
    org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
    common/openjdk_build_pipeline.groovy: 195: [Static type checking] - Cannot find matching method testDoubles.ContextStub#getAbsoluteUrl(). Please check if the declared type is correct and if the method exists.
     @ line 195, column 84.
       tream sign_build FAILED. See ${signJob.g
                                     ^

    common/openjdk_build_pipeline.groovy: 240: [Static type checking] - Cannot find matching method testDoubles.ContextStub#getAbsoluteUrl(). Please check if the declared type is correct and if the method exists.
     @ line 240, column 75.
       am mac installer FAILED. See ${installer
                                     ^

    common/openjdk_build_pipeline.groovy: 278: [Static type checking] - Cannot find matching method testDoubles.ContextStub#getAbsoluteUrl(). Please check if the declared type is correct and if the method exists.
     @ line 278, column 77.
        linux installer FAILED. See ${installer
                                     ^

    common/openjdk_build_pipeline.groovy: 310: [Static type checking] - Cannot find matching method testDoubles.ContextStub#getAbsoluteUrl(). Please check if the declared type is correct and if the method exists.
     @ line 310, column 79.
       indows installer FAILED. See ${installer
```

**Comment by karianna** [comment]
On JDK 11 the test failure is...

```
[Pipeline] echo
matched
[Pipeline] echo
11.0.7+9-202004291156
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] echo
Execution error: No such property: versionInfo for class: Build
```

**Comment by gdams** [comment]
merge conflicts

**Comment by karianna** [comment]
@johnoliver in case he missed it.

**Pull request merged**
