### PR TITLE
Refactor how "vendor" configure arguments are generated

### PR DESCRIPTION
**Pull request by austin0**
The intention of this PR is to clean up and centralise how the `java.vendor.x` properties are set, and to do this in a way that is easily extensible for any future implementations. It also enables a number of properties for jdk8u that were previously only enabled for 9+. These include:
- Vendor URL
- Vendor Bug URL
- Vendor VM Bug Url

I also intend for this to be a solution to https://github.com/AdoptOpenJDK/openjdk-build/issues/1387. The request made in the issue is to set `java.vendor.version` to the the source of the OpenJDK repo, this change has already been made to the `release` file (#2049) and is planned for the the `json` metadata file so seems redundant. I have instead set it to the name of the variant being built (`Hotspot`, `OpenJ9`, `SAP`, `Corretto`, `Dragonwell`, etc). @brunoborges @lumpfish @sxa @gdams  any comments?

Java properties after PR:
```
    java.runtime.name = OpenJDK Runtime Environment
    java.runtime.version = 15+34-202009101534
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 15
    java.vendor = AdoptOpenJDK
    java.vendor.url = https://adoptopenjdk.net/
    java.vendor.url.bug = https://github.com/AdoptOpenJDK/openjdk-support/issues
    java.vendor.version = Hotspot
    java.version = 15
    java.version.date = 2020-09-15
```

Signed-off-by: Austin Bailey <Austin.Bailey@ibm.com>

### CODE REVIEW

**Comment by austin0** [comment]
run tests

**Comment by M-Davies** [comment]
run tests

**Review by sxa — COMMENTED** [review]
Superficially looks like it'll be ok to me, but i'll let others make final judgements on the changes :-)

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
run tests

**Comment by lumpfish** [comment]
What values do you get for an openj9 build?
Also, which releases are affected and in what way?  If users are 'used to' the current values, what changes would they see?

**Comment by austin0** [comment]
@lumpfish the only change from the existing code for jdk11u+ is that `java.vendor.version` will be the build variant (i.e. Hotspot, OpenJ9, etc) instead of the current "AdoptOpenJDK", for jdk8u for following default settings will change. 
Before:
```
java.vendor = AdoptOpenJDK
java.vendor.url = http://java.oracle.com/
java.vendor.url.bug = http://bugreport.sun.com/bugreport/
```
After:
```
java.vendor = AdoptOpenJDK
java.vendor.url = https://adoptopenjdk.net/
java.vendor.url.bug = https://github.com/AdoptOpenJDK/openjdk-support/issues
```

Somebody upstream decided that `--with-vendor-name` should set both `java.vendor` and `java.vm.vendor` so OpenJ9 has a patch to manually change it (see https://github.com/eclipse/openj9/pull/5041).

**Comment by lumpfish** [comment]
Thanks @austin0 , looks good.

**Comment by M-Davies** [comment]
@austin0 I'm going to run tests again. Can you let me know if the results are what you expect?

**Comment by M-Davies** [comment]
run tests

**Review by karianna — APPROVED** [review]
LGTM - but we should check the output carefully.  Does PR Test Builder spit out Dragonwell or OpenJ9 builds?

**Comment by austin0** [comment]
@karianna I've manually checked OpenJ9 and it correctly matches other binaries, I haven't found a way to check dragonwell but I can't conceive any reason for it to break. It seems the dragonwell section will likely change anyway after a decision on what Vendor/Variant/Distribution means.

**Review by gdams — APPROVED** [review]

**Pull request merged**
