### PR TITLE
Add DOCKER_NODE configuration value

### PR DESCRIPTION
**Pull request by M-Davies**
* Allows end users to specify their own docker machine labels

Closes: #2095 
Signed-off-by: Morgan Davies <morgan.davies@ibm.com>

### CODE REVIEW

**Comment by M-Davies** [comment]
To test this, I have added a [temporary docker node label](https://github.com/AdoptOpenJDK/openjdk-build/pull/2100/files#diff-5083fca0f9616f848acf9a4439dd3e70) for openj9 and for hotspot on JDK8 linux. The others config files have remained the same to demonstrate what happens when we don't have a `DOCKER_NODE`
- [JDK8/Linux/HS](https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk8u/job/jdk8u-linux-x64-hotspot/739/console) is correctly looking for a node labelled `build&&linux&&x64&&dockernodetesthotspot`
- [JDK8/Linux/J9](https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk8u/job/jdk8u-linux-x64-openj9/313/console) is correctly looking for a node labelled `build&&linux&&x64&&dockernodetestopenj9`
- [JDK11/Linux/HS](https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk11u/job/jdk11u-linux-x64-hotspot/606/parameters/) `DOCKER_NODE` config is empty, therefore it will correctly use adopt's default node parameter `dockerBuild`

Now I just need to remove the test configs and revert the temp testing change to the PR_Tester

**Comment by M-Davies** [comment]
@AdamBrousseau @gdams Can I get reviews please?

**Comment by M-Davies** [comment]
> #  PR TESTER RESULT 
> ❎ Some pipelines failed or the job was aborted! ❎
> _See the `pipeline-build-check` below for more information..._

This was due to a [windows issue](https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk15u/job/jdk15u-windows-x64-hotspot/176/console) affecting all versions (unrelated to this PR) https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1573
```
12:17:39  rm: cannot remove '/cygdrive/c/workspace/openjdk-build/workspace/./build//src/build/windows-x86_64-server-release/make-support/failure-logs': Directory not empty
```

**Comment by M-Davies** [comment]
run tests

**Review by karianna — APPROVED** [review]
LGTM

**Review by AdamBrousseau — APPROVED** [review]
LFTM. I gave it a test by adding the param to my build and pointing at your code. Seems to work. Thanks Morgan.

**Pull request merged**
