### PR TITLE
Implement fixed trigger schedule

### PR DESCRIPTION
**Pull request by johnoliver**

### CODE REVIEW

**Comment by karianna** [comment]
Fixes #1549

**Comment by karianna** [comment]
@johnoliver fails with:

`/home/jenkins/.jenkins/workspace/build-scripts-pr-tester/openjdk-build-pr-tester/pipelines/jobs/configurations/jdk14u.groovy`

**Comment by jerboaa** [comment]
@johnoliver @karianna: It's been failing like that for a while. Note that JDK 14 doesn't use the jdk14u tree as of yet. it's `openjdk-jdk14`. So my suspicion would be that there is some hard-coding of jdkXXu somewhere.

I might be wrong entirely ;-)

**Comment by johnoliver** [comment]
@karianna yeah that failure will be unrelated to this PR

**Pull request merged**
