### PR TITLE
Replace deprecated triggers with pipelineTriggers

### PR DESCRIPTION
**Pull request by M-Davies**
Fixes: #2288 
Signed-off-by: Morgan Davies <morgandavies2020@gmail.com>

### CODE REVIEW

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
run tests

**Comment by M-Davies** [comment]
run tests

**Comment by karianna** [comment]
@M-Davies  - Did you want to continue with this PR or are you happy to park it given our [refactoring efforts](https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1612353108094700)?

**Comment by M-Davies** [comment]
> @M-Davies - Did you want to continue with this PR or are you happy to park it given our [refactoring efforts](https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1612353108094700)?

Park it. It's not a high priority and the current solution I wanted to roll with isn't possible without the necessary plugins anyway

**Pull request closed without merging**
