### PR TITLE
Allow dockerfile to be built in pipeline

### PR DESCRIPTION
**Pull request by gdams**
## What
This PR allows us to install additional dependencies on top of the default build docker image that we produce.

## Why
We cannot bundle Cuda in our public docker build image, this allows us to run an additional cuda install step local before the build starts:

```dockerfile
ARG image

FROM $image

# Install cuda headers https://github.com/eclipse/openj9/blob/master/buildenv/docker/mkdocker.sh#L586-L593
RUN mkdir -p /usr/local/cuda-9.0/nvvm
COPY --from=nvidia/cuda:9.0-devel-ubuntu16.04 /usr/local/cuda-9.0/include /usr/local/cuda-9.0/include
COPY --from=nvidia/cuda:9.0-devel-ubuntu16.04 /usr/local/cuda-9.0/nvvm/include /usr/local/cuda-9.0/nvvm/include

ENV CUDA_HOME="/usr/local/cuda-9.0"
```

### CODE REVIEW

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by gdams** [comment]
run tests

**Comment by karianna** [comment]
@gdams - We keep seeing these flow interruption breakages on the 11 builds. - any idea why?

**Comment by gdams** [comment]
@karianna yes it's because the codebuild machines don't have enough CPU/RAM. I've told @M-Davies to rebase on master because he'll pull in my commit that switches to Azure

**Pull request merged**
