### PR TITLE
Disable nightly builds while we release the 8u265 update

### PR DESCRIPTION
**Pull request by sxa**

### CODE REVIEW

**Comment by sxa** [comment]
> We enabling ARM 32 C2 builds for this?

Not sure - we'll need to verify that we have the tags for it, and I'd prefer to do a bit more testing ... Gut feel is to err on the side of saying no at the moment since we haven't even looked at the recent builds with it enabled and then look again later (I didn't get the time I'd hoped to to test against 262) It's a risk, but then we do minimal testing against it anyway ;-)

**Comment by karianna** [comment]
@sxa I think this PR should remove that change then?

**Comment by sxa** [comment]
> @sxa I think this PR should remove that change then?

Ah I see - that commit wasn't supposed to be in here :-) I'll rebase properly

**Comment by karianna** [comment]
@gdams do we still need to block nightlies to get a release out?

**Comment by gdams** [comment]
nope this should be good to be closed

**Pull request closed without merging**
