### PR TITLE
Change JDK16_VERSION to jdk16u

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Signed-off-by: Andrew Leonard <anleonar@redhat.com>

### CODE REVIEW

**Review by smlambert — APPROVED** [review]

**Review by sxa — APPROVED** [review]

**Comment by andrew-m-leonard** [comment]
run tests

**Review by M-Davies — COMMENTED** [review]
@andrew-m-leonard Ref https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/pull/100#issuecomment-801187350, if some of the links in that doc are wrong can you go through and update that section please?

**Comment by andrew-m-leonard** [comment]
> @andrew-m-leonard Ref [AdoptOpenJDK/ci-jenkins-pipelines#100 (comment)](https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/pull/100#issuecomment-801187350), if some of the links in that doc are wrong can you go through and update that section please?

@M-Davies that's my plan once i've gone through everything

**Comment by andrew-m-leonard** [comment]
openj9 broken upstream...

**Review by M-Davies — CHANGES_REQUESTED** [review]
https://github.com/AdoptOpenJDK/openjdk-build/blob/6935c13393d8ad4e6d8d005c639f0d56c18cfcff/.github/workflows/build.yml#L16
needs to be updated

**Review by M-Davies — APPROVED** [review]

**Pull request merged**
