### PR TITLE
Revert weekend test release pipeline builds to HEAD tags

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Now the releases are out the way we can change the weekend release test build back to building the HEAD branches.

Signed-off-by: Andrew Leonard <anleonar@redhat.com>

### CODE REVIEW

**Review by M-Davies — COMMENTED** [review]
Is this to be merged during release?

**Comment by andrew-m-leonard** [comment]
> Is this to be merged during release?

no

**Comment by andrew-m-leonard** [comment]
run tests

**Review by M-Davies — CHANGES_REQUESTED** [review]
Can the commit message or description be updated to state why this is necessary?

**Comment by andrew-m-leonard** [comment]
> Can the commit message or description be updated to state why this is necessary?

@M-Davies i've updated the description

**Review by sxa — COMMENTED** [review]
LGTM

**Review by M-Davies — APPROVED** [review]

**Review by sxa — APPROVED** [review]
(Ooops last comment should have beena proper approval)

**Pull request merged**
